### ISSUE TITLE
Portis login

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#1092]
https://docs.portis.io/#/quick-start another username + pass login solution, could be cool to integrate. Looks pretty easy b/c it uses web3

http://fortmatic.com as well

**Comment by pgebheim** [comment]
@joeykrug -- think we should investigate this during a UI sprint (eg target it in V2) or should I put this into the backlog + Post V2?

**Comment by joeykrug** [comment]
It's simple and like 1 day 1 dev time of work and should improve usability by more than that, let's do it in V2 imo!

**Comment by joeykrug** [comment]
Would consider looking @ fortmatic login too (phone # + pin)

**Comment by pgebheim** [comment]
Should definitely do this as a product thing.

Just adding methods doesn't necessarily make things better, since there are more choices, etc.

I think anything related to connecting an account and bringing in funds should be designed out before we do any implementation

Paul
paul@augur.net

________________________________

**Comment by pgebheim** [comment]
Portis Docs:
http://ec2-52-26-194-35.us-west-2.compute.amazonaws.com/x/d?c=3829001&l=780dfe19-8973-4c4f-8168-c086d3c0b542&r=4ff75ee0-a02d-4a47-9678-b82fd5075796

When this goes into Development we'll want @cillianhunter0 @Chwy5 @matt-bullock to take a look and make sure they are fine with adding another login option + see if there's anything else we'd wanna update around it,

**Comment by Chwy5** [comment]
Can probably be added to the timeline for 1.14 or post 1.14 pre v2
