### ISSUE TITLE
Augur Community Bounties 

### ISSUE THREAD

**Issue by ghost** [AugurProject/augur#1116]
![](https://cdn-images-1.medium.com/max/2000/1*0sxSCaD_rT7SuazRLCXz7g.png)

The Forecast Foundation and the Augur community is excited to launch additional bounties for Augur tooling and infrastructure. Thus far, the network of developers, front-ends, dashboards and more have all grown and developed organically; allowing for peer-to-peer prediction markets to take many unique forms.

This bounty initiative will seek to further that expansion by encouraging developers in building applications and tooling that improve the usability, growth, and effectiveness of the Augur platform. Now is your chance to get acclimated with the development team, community, and code — while earning a bounty, improving the ecosystem, and beginning your own project!

### The Procedure:

1. The Forecast Foundation and the “_Smarty Pants_” group of Augur Discord users will specify requests for external Augur tooling and applications on the Augur Github. Applicants are also encouraged to submit ideas for apps, projects, and additional tooling that are not explicitly outlined in this initiative on the same Github issue.

2. Applicants will write a short response detailing their experience, vision, proposed milestones and timetable, and plans for building out the project on the public GitHub issue.

3. Applications for each project will be open for (7) days. The Foundation and Smarty Pants group will review each application and promptly approve, deny, or request more information. **The 7 day period begins Friday, February 22nd, 2019 at 5:00PM PT, and ends the following Friday, March 1st, 2019 at 5:00PM PT.**

4. Upon the completion of the (7) day public application process, the Foundation and Smarty Pants group will set the top three teams or persons for each submission, where number 1 has initial priority, number 2 second, and number 3 third.

5. Developers who have been selected as the number 1 team for initial priority will be required to have deliverables by a certain date, else the team or person defaults on the bounty and it gets passed to the next team in line. If you submitted your own project or idea, its eligibility will be determined using the same criteria as the example projects below.

6. Upon completion of the project and by approval of the Forecast Foundation and the Smarty Pants group, the bounty will be complete and paid out to the submitting team or persons.

**_“Smarty Pants” is a group of independent, community individuals who have proven their extensive knowledge of Augur in the Discord chat. They are the moderators of the Augur Discord, and will be assisting in this initiative as an unbiased control group outside of the Forecast Foundation._**

### Project Ideas:

- **Consumable Glossary:** Take the Augur Glossary (in the [Augur Docs](https://docs.augur.net/#glossary)) and create some sort of crash course / means of digesting and consuming the terms, with clean deep-linking to important concepts. You should create something where anyone who wants to learn more in depth about Augur can easily consume the details surrounding forks, reporting, trading, different states of Augur, etc. Think of example websites made by RadarRelay for example: [WETH.io](http://weth.io), [Gwei.io](http://gwei.io), [EthGas.io](http://ethgas.io), etc. **_($2,750 in REP)_**

- **Augur Explainer Video:** Check the [old Augur explainer video](https://www.youtube.com/watch?v=yegyih591Jo) for reference. Create something similar, however up to date with the current mechanisms and explanations of how Augur works (_including changes being made to the v2 deployment of Augur on a protocol level_). **_($4,000 in REP)_**

- **Historical Reporting Digest:** A running wiki/index and analysis of key precedent set by Augur REP reporters during disputes. A central repository where anyone can learn about the historical decisions REP reporters have made in terms of invalid markets, disputes, ambiguous markets, etc. **_($2,000 REP)_**

- **Augur Analysis Services:** More third-party analysis services. Amount of REP remaining in old reporting fee window stats, historical reporting rounds REP staked amounts, accurate display of DAU, an “_Augur Calendar_” that shows the important upcoming dates for protocol events, visualizations of volume & trading activity, etc). Submit your idea on the GitHub issue. **_(~$2,500 in REP, variable)_**

- **Submit Your Own:** Submit your own idea for a project.

### How to Apply:

Please answer the questions below in a reply to this issue: 

```
What project do you want to build?

Who are you, and why do you (or your team) want to build this? 

Outline your plans for completing the bounty, including rough milestones and timelines: 

Links to your Github, other project contributions, Twitter, Website, etc:

Anything else you'd like to add:
```

**Comment by easybreezy1** [comment]
I'm crypto-enthusiast who is a teacher by day and enjoys video making.  I love trying to educate people about the crypto/blockchain space in a way that is accessible and easy to understand.  I'm particularly passionate about projects that look to make a positive change in the way our society works and interacts, which is evident with Augur!

I'd be very interested in creating a video for the Augur project that sets itself apart from other projects.  I feel that there is a lot of projects that use animated explainer style videos to promote their project.  While using animation does make it easy to understand, I am a strong believer in an emotive call-to-action, giving people the ability to see the big picture and a reason to become involved.  I believe this is more possible through cinematic 'wanderlust' style films that many corporations are starting to use.

I propose to create a short film/video helping to:
a) explain the tech/mechanics of the project and;
b) develop a sense of purpose and excitement

The suggested reward of $4,000 is what I typically offer to make videos, and that would include licensed music and footage, script writing and voice over.  I would endeavour to fulfil the bounty within 5  weeks of acceptance.

A sample of my work can be found here:
https://www.youtube.com/watch?v=08_pLmckl0U
https://www.youtube.com/watch?v=0wx2XJQxS74

Thank you for your consideration. All the best with the project and picking applicants :)

**Comment by msagansk** [comment]
I would like to tackle the Consumable Glossary project. I have been following Augur for the past couple years and I have built up meaningful knowledge through trial and error, the Augur Discord, and I am one of the "Smarty Pants" (note that I will abstain from participating in the selection process). 

Prior to this bounty, I had already started https://augur.guide in my spare time as I recognized the community's need for such a project. If I am selected, I will be able to commit full-time hours into the work, allowing for a much faster completion of "version 1.0". I estimate that I would be able to fulfill the requirements of the bounty within 4 weeks of being selected. Please visit the site as it exists today to get a sense of the scope, layout, and writing style. 

Augur.Guide is hosted on Github Pages and is open source under the MIT License. This allows for the community to assist with improving it over time through issues, pull requests, etc. I look forward to being given the opportunity to help grow the Augur ecosystem. Thank you.

**Comment by Anish-Agnihotri** [comment]
Hello!

My name is Anish and I’m a student developer who has been working on building platforms and decentralized applications backed by blockchain technologies for the past few months. I’ve been experimenting with Augur and various tools built atop its core principles for simplifying various aspects of the platform (utilities like Veil or Predictions.Global, now also a part of Veil), and have been incredibly fascinated by its potential use cases. 

I’ve participated in quite a few markets so far, albeit not being the best predictor – haha, but it has given me an insight into how they function and the Augur protocol as a whole. Thus, at this point of time, I’m applying for a community bounty to potentially further not only my understanding of Augur, but also build tools using my existing skillsets for the community.

**What project do you want to build?**

I’m most interested in building an Augur Analysis Service. Data visualization is one of my personal hobbies and this would fit very well within that context. I’m a fan of tools like Predictions.Global and have worked with the Augur decentralized oracle API in the past for personal projects. 
Under this bounty, I’d like to build two things: 
1.	An easy to use web platform that is accessible across networks, resolutions, and devices. Ideally, I’d like this web platform to be UI/UX-friendly with easy and convenient statistics and information being displayed. I would use a MERN-stack to accomplish this along with a mix of centralized data sources (potential to inhouse through a seperate node deployment), and the existing decentralized oracle. An example of an existing web platform similar to this which I would take inspiration from is the [Uniswap.Info Beta Portal](http://beta.uniswap.info/) which beautifully displays information across all devices, and is easily understandable for the average user (see additional examples + images below). In the same way, I'd like to build a similar portal for Augur. Since I’m a blockchain developer at heart, deploying this platform to an IPFS endpoint with an ENS domain name would also be part of my development, since at the end of the day, I’d like to keep this tool as open, accessible, and decentralized as possible.

2.	The second part of this bounty would be an easy to access API endpoint utility for important information served by the web platform. Currently, there are few solutions for querying Augur market data and other information (like the calendar of important events), and to solve this I'd like to develop a GraphQL outgoing API endpoint alongside the web platform, that other developers can utilize and easily incorporate into their own projects, thus, encouraging further developer involvement in the community.

Additional examples + images:

1. Uniswap Info
![uniswap](https://user-images.githubusercontent.com/4398624/53460567-92980b80-3a0b-11e9-9fea-6f5df88e7e8a.JPG)
2. Dai Stats
![daistats](https://user-images.githubusercontent.com/4398624/53460576-988dec80-3a0b-11e9-9bc6-8f95c91d8b3b.JPG)

**Who are you, and why do you (or your team) want to build this?**

I’m a student full-stack developer who has been interested in blockchain and crypto-currency for the past two years. I’m best with web technologies including but not limited to:
1.	HTML, EJS, PUG, Handlebars
2.	SASS, SCSS, CSS, LESS
3.	JS, Babel
4.	NodeJS

I have also completed the Consensys Developer Academy bootcamp and am moderately proficient with Solidity.

As a frequent user of prediction markets (mostly for personal entertainment) and a developer at heart, I’d love to make it easier for users to access data about Augur markets, the projects calendar, and other network insights, and make it easier for developers like myself to integrate that same data into their own applications.

**Outline your plans for completing the bounty, including rough milestones and timelines:**

If approved to begin working towards this bounty, these are the rough milestones and timelines that I would aim to follow: 
1.	**Week one**: Beginning repository, initiating setup of development environment + development wireframes, outlining plan of action and writing technical spec.
2.	**Weeks two to four**: Developing a responsive front-end in React, followed with a back-end querying centralized endpoints, and the decentralized oracle using NodeJS. **Note:** There is the potential to setup a node to serve data regarding Augur at this point, although I'd have to take a further look at this if approved for the bounty.
3.	**Week four to five**: Working on exposing a safe GraphQL endpoint for platform-served data.
4.	**Weeks five to six**: Conducting project optimizations (auditing with pagespeed, GTMetrix, etc.), doing user testing, and making final changes. 

All in all, I’d estimate the project to take approximately six weeks of time from inception, and upwards of 80 man-hours for me to complete.

Due to the scope of these community bounties, I assume that the payment will be in a lump-sum upon delivery. Though, in the case that that is not true, I will be tracking my contributions and milestone achievements through a decentralized platform like [Giveth](https://giveth.io) to stay accountable to progress.

**Links to your Github, other project contributions, Twitter, Website, etc.:**

1.	My Github profile can be found [here](https://github.com/anish-agnihotri).
2.	My resume (outlining my development experience) can be found [here](https://anishagnihotri.com/assets/documents/Anish%20Agnihotri%20-%20Resume.pdf).
3.	My personal website can be found [here](https://anishagnihotri.com/).
4.	My twitter can be found [here](https://twitter.com/_anishagnihotri).
5.	My Gitcoin profile (showing past successful bounty experience working with various decentralized projects, and others via open-source contributions) can be found [here](https://gitcoin.co/profile/anish-agnihotri).
6.	My Devpost profile (showing my speed and efficiency building DAPPS and other platforms in a short timeframe) can be found [here](https://devpost.com/348712712).

As for specific project contributions, I'd be happy to provide relevant experience. For example, I just recently completed an overhaul of the DAppNode website visible [here](https://dappnode.io/).

**Anything else you’d like to add:** 

If any further clarification is required, etc., please feel free to reach out. I'd be happy to have a chat.

Thanks for the bounties, I look forward to seeing all the great projects built as a result :)!

**Comment by 24msP** [comment]
What project do you want to build?

I was interested in the project Augur for a long time, and a month ago I began to actively engage in preparing for the release of the video, I already have a basic scenario that I want to improve in the process, I also have material and sketches of infographics for the video.
I want to create Augur Explainer Video only in a slightly different format, I want to make a video in pop-science style, where it would be told in an interesting and simple language not only about the project itself, but also about the ideas and areas on which it is built (history and ways the use of prediction markets, wisdom of the crowd, Hayek's economic theory and more)

Who are you, and why do you (or your team) want to build this?

I think that there is not enough pop-science content in crypto space that could be interested  people outside crypto. My goal is to create a video that can be interesting, giving knowledge and understandable to anyone.

Outline your plans for completing the bounty, including rough milestones and timelines: 

I plan to finish the video in 4-6 weeks! At the moment I work every day so that the release of the video was as early as possible. I want to make a plot according to my script with video infographics, inserts of other video materials and voice acting.

Links to your Github, other project contributions, Twitter, Website, etc:

This is my first video in the cryptospace,  it turned out that to start my project, I chose Augur, and after that I saw this program.
I hope that the work will be done qualitatively and will be distributed to the masses.

my mail: yntro24@gmail.com
my twitter link: https://twitter.com/yntro24

Anything else you'd like to add:

I will anyway make a video about Augur. And if my video can get a reward, it will be great, but this is not the main goal. I just want to make a video about the project, which I have long been interested in and follow him.

**Comment by SebastianMetzger** [comment]
**About AugurInsider**
I want to continue work on www.augurinsider.com after it lost a little bit of momentum since last year’s markets expired and not so many new currency derivative markets got created at the beginning of this year.

![image](https://user-images.githubusercontent.com/2345498/53582704-44584900-3b80-11e9-815c-b7d39568ae51.png)

The goal of AugurInsider is to provide KPIs for currency derivatives on Augur based on the [Black Scholes](https://en.wikipedia.org/wiki/Black%E2%80%93Scholes_model) formula that are common for stock options and future options in traditional broker interfaces. This is valuable information for traders, who want to hedge or speculate based on volatility metrics.

A possible step in the very future, when liquidity in Augur is way up might be to create markets based on volatility metrics, like ones that are available for classic stock markets like [VIX ](http://www.cboe.com/vix) or [VXX ](http://www.ipathetn.com/US/16/en/details.app?instrumentId=341408) ETNs.

There might also be ways to do this completely decentralized ideally, but this is not thought through yet.

**About me**
I am the CTO and co-founder of a SaaS startup based in Germany. (-> www.snapaddy.com) I started programming 20 years ago, became a full-time entrepreneur 5 years ago and I am now responsible for a development team with almost twenty people.
On the side I am super excited about the whole Blockchain/Ethereum space and I am especially bullish about everything surrounding decentralized finance. I play around with stock options a bit and I am also interested in finance and economics in general, which let me to the idea for this as a side project, as I am not able to do much programming in my main job anymore 😉
Receiving the opportunity for this bounty would give me additional motivation to continue to work on this in the future.

**Milestones**
_End of April:_ Reanimate augurinsider.com and integrate scalar markets, that are popular for derivatives on veil.co for example.

_End of June:_ Also display historical data and charts, which will make the stats and site more appealing and meaningful.

_Till the end of 2019:_ Here it gets a little bit more nebulous: Create markets based on Volatility KPIs, experiment with ways of a completely decentralized way of doing this etc.

**Links**
www.augurinsider.com
https://medium.com/augur-insider
https://twitter.com/augurinsider

**Comment by AJA191** [comment]
**What project do you want to build?**
I would like to take on the Augur Explainer Video

**Who are you, and why do you (or your team) want to build this?** 
Hi! I am an entrepreneur and I own and operate my own video production company and have been doing it professionally for about 8 years now. I focus on creating the highest quality content that gets seen by the masses and believe I can apply my skills to create a high quality video for Augur to make adoption easier. I also have my degree in finance so I understand the financial side and mechanics of Augur which I think is vital to creating the best possible video. 

Aside from my skillset, I have been deeply interested in the crypto space for a while now and have spent an unhealthy amount of time researching and educating myself on the technology. It is 100% some of the coolest and most powerful technology i've seen in my life and I just love it. 
Augur is one of the most fascinating dapplications i've come across and I see the potential for what Augur makes possible and I would love nothing more than to help bring that to fruition by creating content that is interesting and easily understandable by the average person.

I can envision this video going a couple of ways depending on what the Smarty Pants group's ultimate goal is. On one end of the spectrum, we could create a video that explains easily and simply what Augur _is_, something easily digestible that makes it _click_ for the average person, to the other end of the spectrum that is an in depth explainer of how Augur functions and how to use it. I think both ends of the spectrum have different audiences and I think the question is who do you ultimately want to reach with this video? Perhaps there needs to be multiple videos, which I am more than willing and would love to do. 

I think creating an entire series of videos would be beneficial to Augur and if I were to submit my own idea, it would be to do that. I would love to discuss that further if the Smarty Pants are interested. I have many ideas for videos I would like to see exist. I think I could help Augur get mass attention and I have the track record for doing just that for other projects.


**Outline your plans for completing the bounty, including rough milestones and timelines:** 

- **Phase 1** - **Pre-production** ~ roughly 2-3 weeks

  - Step 1.1 - Communicate with Smarty Pants group and brainstorm/determine what exactly we need to create. How in depth does it need to be, who are we ultimately wanting to reach, etc.

  - Step 1.2 - Create outline and storyboard for video

  - Step 1.3 - repeat steps 1.1 and 1.2 until video idea is finalized


- **Phase 2** - **Production** ~ roughly 4-8 weeks

  - At this point we should have everything figured out during the pre-production phase so all there is to do here is put my head down and create it. Along the way I would keep up to date with the Smarty Pants group so we can make adjustments/changes as we see fit.

  - Step 2.1 - Shoot any scenes needed if it is not all graphics and animation. Maybe we use a model similar to how they used Margot Robbie in The Big Short to explain concepts? [Link to scene](https://www.youtube.com/watch?v=anSPG0TPf84). Just a thought, could be funny... could be stupid ha just so many ways this video could go.

  - Step 2.2 - Edit together. Including audio work, graphic/animation work, general editing work, color grading, etc.

  - Step 2.3 - review, adjust, and repeat steps 2.1 & 2.2 as needed

   ------ Side note: this timeline is only an estimate, some projects take weeks, and some projects take months. It all comes down to what we ultimately decide to make. What I can guarantee though is that whatever we make will be of the highest quality.  -----

**Links to your Github, other project contributions, Twitter, Website, etc:**
- [My youtube](https://www.youtube.com/user/hamnerandpals)  -  The videos you see here are a different type from what this Augur video would be, but I hope these are an example to my level of production and attention to detail to creating quality videos. While there are no graphic/animation specific videos on my channel, I do have experience and knowledge of how to do them, so creating animation graphics like in the original Augur video would be no problem. I also have team members that are highly experienced in VFX work if anything more than graphic animation is needed.

- [Vimeo channel with some other videos i've made](https://vimeo.com/user42043026)

- I do also have other videos i've made for clients that aren't necessarily uploaded all in one place so if you would like to see more examples of my work, let me know.


**Anything else you'd like to add:**
Augur is rad and its possibilities are rad. Let's get the world to understand why that is. I would be proud to help.

**Comment by Cryptovideos** [comment]
**What project do you want to build?**
I would like to take on the Augur Explainer Video

**Who are you, and why do you (or your team) want to build this?**
My name is Evan, im a South African chap that loves spearfishing, surfing and animals!

I also LOVE my job, my clients and the many meaningful relationships formed over the years 

Im a professional Video and motion graphics artist. Iv been creating and producing various Corporate and Blockchain projects for number of years now as a digital agency based here locvally that also pushed out media on a global scale. 

I have a fantastic relationship with all the companies i represent and it is because of my timeous project turn around times, visually engaging high quality media productions and superior customer service that i am blessed to enjoy repeat work and an excellent track record of client testimonials.

My work speaks volumes for itself and i would love to not only produce this project, but others i have in mind on some new ideas thereafter as well!

i take a strong interest in all my clients and it would be a complete honour to produce the Video for you 


**Outline your plans for completing the bounty, including rough milestones and timelines:**

    * **Phase 1** - **Pre-production** ~ roughly 1 week
      Includes script screatin , submission for approaval

    * **Phase 2** - **Production** ~ roughly 2 weeks
      Once the script is sorted, ill handle the Voice Over Production "Broadcast Quality "
      Animation work will follow, then the editing, grading and post production.

Lastly, ill submit for review and can make any tweaks, adjustments that are needed.

**Links to your Github, other project contributions, Website, etc:**

** [Website](www.motionfactory.co.za) **   

** [My youtube](https://www.youtube.com/channel/UCtNcY-1-eOS7jvvdP6fL1Ig/videos?view_as=subscriber) **

**Anything else you'd like to add:**
Team, i think you should take advantage of me, i do everything myslef and its all included, Voice Over Production, Logo Animation, Motion Graphics, Sound Design, Color grading, Post Production....and so on and so on... you really get it all sorted with me!

**Comment by motionfactory-digital** [comment]
**What project do you want to build?**
I would like to take on the Augur Explainer Video

**Who are you, and why do you (or your team) want to build this?**
My Name is Evan, i am a highly energetic motivated and dynamic individual that owns my video production and motion graphics agency.

I reached out some time ago looking to get involved with the project "via Discord - and spoke with a helpful chap -PeterV#9584"....at that particular time no opportunities were available i believe...since then iv been grinding out content for a number of awesome projects like 
https://nem.io/  
https://www.factom.com/

recently, it was brought to my attention that this is the right time to chat and apply ...and i decided to reach out and offer my services :)

**Outline your plans for completing the bounty, including rough milestones and timelines:**

    * **Phase 1** - **Pre-production / script creation** ~ 1 week
create the script, submit for approval, tweaking and fine tuning if need be....
      

    * **Phase 2** - **Production** ~ 2 weeks
Logo Animation, Voice Over Production, Sound Design, Motion Graphics Animation, Grading, Post production, Submission for changes / approval.
      
My youtube Channel  https://www.youtube.com/channel/UCtNcY-1-eOS7jvvdP6fL1Ig/videos?view_as=subscriber   
a mix of various work done over the last few months , just hosted here as demo work and a library of refernaces i can revisit from time to time or to showcase to clients for idea generation and motivations on various animations styles, concepts etc etc

My Website                http://motionfactory.co.za/
i recently just built my own website myself - it was my first attempt and ill be updating it as soon as i get some spare time.

**Anything else you'd like to add:**
I take my work seriously, i love what i do and i believe you have found the perfect match for the video project. look at my work you should see for yourself quite clearly that i am the right fit with the experience suited for the task at hand. 
lets make a big impact and make this video awesome!!

**Comment by strike9ine** [comment]
**What project do you want to build?**
I'd like to create the Historical Reporting Digest.

**Who are you, and why do you (or your team) want to build this?** 
I'm a long time REP speculator, Augur fanatic, and may or may not be among the top traders on Augur in terms of profit. I have experience in web development and have created a simple web dapp from scratch and launched it publicly, where it proved to be secure and worked as intended. Over the past two months I have held REP steadily and finally began dabbling in market reporting. Before then I had been active on Discord, sharing my opinions about how disputed markets should resolve, and weighing the opinions of others. I believe the "rules" of reporting are still entirely too vague and I'd like to shine a light on them and how they are interpreted or created through precedent. I recognize the importance of [reporters.chat](https://reporters.chat/), but I think a website meant to inform reporters about precedents set through past disputes is now beyond overdue.

**Outline your plans for completing the bounty, including rough milestones and timelines:** 

- **Week one:**
    - Share thoughts with the Smarty Pants group to make sure we have a similar vision for the project
    - Research similar projects
    - Create a rough mock-up
- **Weeks two - four:**
    - Build the website with filler example content
    - Attempt to make the site compatible with as many browsers / devices as possible
    - Launch example site for approval from Smarty Pants group if necessary 
- **Weeks five - six:**
    - Replace example content with final content
    - Interview reporters on the Discord, research reporters.chat and other resources for unique angles
    - Bug test
- **During and beyond finalization:**
    - Open source the website so others can run their own Historical Reporting Digests
    - Continue to run my own version of the website, updating it as new disputes come and go

**Links to your Github, other project contributions, Twitter, Website, etc:**
In the interest of staying anonymous with regards to my dapp and the Ethereum address associated with it I have taken it down, along with projects published on the same Github.

**Anything else you'd like to add:**
I have been continuously involved with Augur and REP since r/reptrader was the only place you could get any, and have successfully worked toward making a career out of my involvement. I would love to run this website in perpetuity to do my small part in making Augur more successful.

**Comment by petervecchiarelli** [comment]
@easybreezy1 @msagansk @Anish-Agnihotri @24msP @strike9ine @Cryptovideos @SebastianMetzger @AJA191 Thank you all for applying, we will be deliberating and make an announcement on who is approved Monday!

**Comment by ghost** [comment]
Thank you to everyone who submitted an application! After reviewing the entries with the smarty pants groups, the following have been selected for this initial round of community bounties:

--------------------------------------------------------------

**Selected Initial Applicants:** 

Consumable Glossary: @msagansk [[Application](https://github.com/AugurProject/augur/issues/1116#issuecomment-466691383)]

Reporters Historical Digest: @strike9ine [[Application](https://github.com/AugurProject/augur/issues/1116#issuecomment-468765615)]

Augur Analysis Service: @Anish-Agnihotri [[Application](https://github.com/AugurProject/augur/issues/1116#issuecomment-467693731)]

Augur Analysis Service: @SebastianMetzger [[Application](https://github.com/AugurProject/augur/issues/1116#issuecomment-468347102)]

--------------------------------------------------------------

To the four above, please create a new Github Issue on this same Augur Repo for your project: 

**Title**: "[Community Bounty] My Project Name"
**Issue**: Please describe your project, proposed milestones, timeframes, in more detail. This will be the homepage for your issue. Please include your ETH address, 50% of the payment will be made at the approximate half way mark of your bounty completion, and the other 50% upon completion. 

We will follow up on your GitHub issue and keep in touch on your status, and please join the Augur Discord channel if you're not in there already, we can connect you to the smarty pants group to chat and brainstorm if you'd like. 

--------------------------------------------------------------

This is the first round of these community bounties, and after discussion, it was decided to hold the video bounty until Augur v2 is finalized. There will be a significant amount of changes coming in this release, and we feel it only makes sense to ensure a new explainer video is accurate and up to date. We plan to include this video bounty again in the next round, when the protocol details of v2 will be finalized. @easybreezy1 @24msP @AJA191 @Cryptovideos - thank you all for your applications, your submission will be automatically rolled into the next round!

Thank you once again all for your submissions, we look forward to seeing what gets built! :-)

**Comment by petervecchiarelli** [comment]
@strike9ine Please create an issue describing your project, proposed milestones, timeframes, in more detail. This will be the homepage for your issue.

**Comment by 24msP** [comment]
@tomkysar @petervecchiarelli
Hello. I did not wait for the release of  V2 and I’ve already made a video. I think that when V2 comes out I will make one more video about it. And also about companies building on top of Augur protocol.
My video consists of four parts:
1. Prediction Markets
2. The Wisdom of  Crowds
3. History of Prediction Markets
4. Augur: a Decentralized Oracle and Prediction Market Platform

Link: https://www.youtube.com/watch?v=UlFb91ZDFWQ

If you think my work is worthy of an award, I will be very happy. 
Thanks for attention

My mail is: yntro24@gmail.com
My tweet about video: https://twitter.com/yntro24/status/1130880336798203904
