### ISSUE TITLE
augur app sync file not getting deleted before added.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1129]
https://www.reddit.com/r/Augur/comments/auphlo/augur_app_now_tries_to_create_warp_sync_file/?st=JSKTSDQW&sh=a558a814

looks like issue where sync file gets bigger and bigger or old sync file doesn't get deleted when new one gets created.

Need to disable on linux and make generating warp sync file configurable.

**Comment by pgebheim** [comment]
I can try to repro this -- maybe @justinbarry can add a checkbox to the UI to allow turning off warp generation?

**Comment by morninglite** [comment]
Hi, I'm the reporter. It happens 100% of the time for me. What can I do to help debug? I'm already building from [source](https://github.com/AugurProject/augur-app/tree/v1.10.2)

**Comment by morninglite** [comment]
I also forgot to mention, the files in question appear to be anonymous -- so the space used show up in `df`, which queries the filesystem itself, but not in `du` which scans directories. I only know it's Augur because the space comes back instantly as soon as the app is closed.

I think this means the app is `unlink`ing the file(s) but continuing to write to them afterwards.

**Comment by bthaile** [comment]
https://github.com/AugurProject/augur-node/blob/47d634f41134c84bcb866546c51994613e9af40f/src/sync/file-operations.ts#L70

Here is the code that is suppose to be removing all .warp files

**Comment by morninglite** [comment]
Thanks for pointing me at the right direction. I took a closer look, and it turns out the offending files are not the warp sync files themselves, but the temporary `__fixed_db_file__` created [here](https://github.com/AugurProject/augur-node/blob/47d634f41134c84bcb866546c51994613e9af40f/src/sync/file-operations.ts#L17). This can be ascertained by running the `lsof` tool, which lists open file descriptors, on the augur app after it's been up for a while. It will show a couple dozen open files like this:

```
augur   5090  mlite  108u      REG              253,3 186118144  1184557 /home/mlite/.augur/__fixed_db_file__ (deleted)
augur   5090  mlite  109u      REG              253,3 186155008  1184578 /home/mlite/.augur/__fixed_db_file__ (deleted)
augur   5090  mlite  110u      REG              253,3 186167296  1184577 /home/mlite/.augur/__fixed_db_file__ (deleted)
augur   5090  mlite  111u      REG              253,3 186179584  1184583 /home/mlite/.augur/__fixed_db_file__ (deleted)
augur   5090  mlite  112u      REG              253,3 186195968  1184069 /home/mlite/.augur/__fixed_db_file__ (deleted)
```

So unless I'm missing something, either the ReadStream created [here](https://github.com/AugurProject/augur-node/blob/47d634f41134c84bcb866546c51994613e9af40f/src/sync/file-operations.ts#L50) never gets destroyed, or the Knex created [here](https://github.com/AugurProject/augur-node/blob/47d634f41134c84bcb866546c51994613e9af40f/src/sync/file-operations.ts#L99) doesn't close its file descriptor when finished.

**Comment by morninglite** [comment]
Looks fixed for me with https://github.com/morninglite/augur-node/commit/e759812fb0b7ba1f695e70801593ee7e2a097caf

To test, I also reduced the `DUMP_EVERY_BLOCKS` to 5 and it doesn't seem to leak these files anymore.

**Comment by morninglite** [comment]
PR here: https://github.com/AugurProject/augur-node/pull/823
