### ISSUE TITLE
Incorrect amount displayed for profi in order ticket of Trading pg

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1208]
Cat 3 market, already have positions in each outcome, short 1 AA, Long 1 BB, and Long 1 of outcome CC......The math is incorrect in the order ticket for profit.  The message is correct I want to buy back 1 share at .2 (that i am short at 0.35).... Profit should show 0.1499 = (0.35-0.2)-.0001(est fee)

![3-2cat3short1-covering](https://user-images.githubusercontent.com/41301809/53684501-1425bd00-3cdc-11e9-9e50-aefc61a78588.jpg)

**Comment by bthaile** [comment]
short position total cost = (max - price) * quantity = 1 - .35 = .65 * 1 = .65 ETH
closing cost = price * quantity = 1 * .2 = .2 ETH
I'm confused seems the profit would be = .65 - .2 = .45 ETH (minus fees)

**Comment by Chwy5** [comment]
the closing cost would be (Max - closing price) * quantity
(1-0.2)*1=0.8
profit would be closing position - short position = (.8 - 0.65)= 0.15

**Comment by bthaile** [comment]
Isnt the closing a long so the cost is price * quantity. Just 0.2 eth

**Comment by Chwy5** [comment]
The simple way I do it...is just (avg price of short position - limit price )* Quantity
 So if i sell 10 shares at .4 and buy 10 shares back at .3....I make .1 per share * 10 shares

**Comment by bthaile** [comment]
I think I'm following you, when closing out a short calculate cost of long as though it was a short.
I did an example on sneakpeak that proves your point:

starting user balance 0.291257424321761052 Ether
new short position 0.1 @ 0.7 cost is 0.03 Ether (gas cost: 0.001588406)
after order balance 0.259669018321761052 Ether (Eth used 0.031588406, this is adds up correctly)
-- all of this is correct

close short .1 @ .89 cost is 0.089 Eth
(we incorrectly show this) profit is 0.03 - 0.089 = -0.0590 Eth
-- we should calculate the long order cost as though it's a short since it's closing a short
-- it should be 1 - .89  = .11 * quantity (0.1) = 0.011
-- so profit would be 0.011 - 0.03 = -0.019 Eth

Here is what happened:
user balance 0.259669018321761052 Eth
closing short transaction gas cost: 0.00093476 Eth
ending Eth balance: 0.269734258321761052 Eth

Summary:
total trade cost, starting balance - ending balance
total cost 0.021523166
gas fees: 0.001588406 + 0.00093476
total loss 0.019 ETH after gas fees

**Comment by bthaile** [comment]
I've addressed the `Profit` in order form confirmation. updated sneakpeak, ready for testing.

**Comment by Chwy5** [comment]
reviewed and fixed
