### ISSUE TITLE
Implement tax data export API in Augur-State

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1448]
- [x] Include Transfer events

**Comment by pgebheim** [comment]
Proposal is to implement this by exporting in the following format or one similar to it:

```
Date (date and time as YYYY-MM-DD HH:mm:ss Z)
Source (optional, such as an exchange name like MtGox or gift, donation, etc)
Action (BUY, SELL or FEE)
Symbol (BTC, LTC, DASH, etc)
Volume (number of coins traded - ignore if FEE)
Currency (specify currency such as USD, GBP, EUR or coins, BTC or LTC)
Price (price per coin in Currency or blank for lookup - ignore if FEE)
Fee (any additional costs of the trade)
FeeCurrency (currency of fee if different than Currency)

For example:
Date,Action,Source,Symbol,Volume,Price,Currency,Fee
2014-01-01 13:00:00 -0800,BUY,Online,BTC,1,500,USD,5.50
```

In this case:
- Share Token Address would be the currency.
- Transfers in/out would just be a Type "TRANSFER"

**Comment by pgebheim** [comment]
@Chwy5 -- Is the transaction history as-is "good enough" for launch or do we need anything more from your perspective?

**Comment by Chwy5** [comment]
The Info we are providing is good for launch, though I am seeing some bugs:

Market creation only shows the dai portion of the transaction, not seeing the rep bond.  Also not seeing the transaction Fee

For trading when a trade occurred not seeing the Fee hit up

**Comment by pgebheim** [comment]
This feature is currently implemented as the Transaction History. In order for it to work for real financial purposes, you'll need to get all time history -- which will not exist in the V2 UI because of data pruning reasons.

This feature is currently addressable with an SDK server mode with a config that will tell the server to not use warp sync. Without warp sync the node will fully bulk sync and then all data will be available to any UI connected to it.  In the future we may want to explore having a button in the UI that will attempt to bulk sync all the data.

That feature will be tracked here -- https://github.com/AugurProject/augur/issues/6993.
