### ISSUE TITLE
Holdings Issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#145]
My account has holdings from other accounts on it (things I've never bought)

**Comment by tinybike** [comment]
I suspect this is caused by the multi-node RPC feature defaulting to the "coinbase" account; for the hosted nodes, this is the demo account.  Will comb through augur.js tomorrow to try and isolate where this is happening.  Closing this issue and moving over to augur.js b/c I'm nearly certain this is a middleware issue.
