### ISSUE TITLE
Graph price history

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur#155]
Retrieve a markets price history for some source such as ethereum logging for graphing results.

**Comment by tinybike** [comment]
Filters should be fixed (AugurProject/augur.js@50eccb367f059aea956eb94a02fdd44f43dae4f4), as well as the price logging functions built around the filters.  To use this functionality:
```javascript
augur.getMarketPriceHistory(marketId, outcomeId, callback);
```
As usual, if you supply a callback function, it's asynchronous; otherwise, it just returns the prices.  The prices are returned as an array-of-objects, organized like:
```javascript
[ { price: '0.99999999999999840752',
    cost: '-0.99999999999999332966',
    blockNumber: '6555' },
  { price: '0.99999999999986041721',
    cost: '-0.98178965763164964336',
    blockNumber: '6553' },
  { price: '0.53508762781669690425',
    cost: '0.80804640374997185019',
    blockNumber: '6060' } ]
```
(The values are actually BigNumbers, displayed as strings here for readability.)

**Comment by tinybike** [comment]
Price history is now available without adding significant extra loading time via [marketeer](https://github.com/AugurProject/marketeer).  So, now all that's needed is to plot the results.  I think [Highcharts](http://www.highcharts.com/stock/demo) will be a good fit.

**Comment by tinybike** [comment]
Added in c9c5ecd10cc1af3d258b97a42fc42bca081d27ef.
