### ISSUE TITLE
Add gzip accept header when fetching logs in augur-state

### ISSUE THREAD

**Issue by brianosaurus** [AugurProject/augur#1567]
Currently we aren't requesting gzipped logs from the ethereum nodes. Adding this will increase performance significantly.

Add this header to our XMLHttpRequests when we fetch logs
```
Accept-Encoding: gzip, deflate, br
```

The JSON RPC provider constructor accepts a ConnectionInfo object in the constructor. This object allows you to specify custom headers: https://github.com/ethers-io/ethers.js/blob/master/utils/web.d.ts#L7

If we do that on the JsonRpcProvider we pass into the EthersProvider, that should allow us to use gzip.

**Comment by adrake33** [comment]
@pgebheim @justinbarry I tried enabling this, but it looks like `Accept-Encoding` is a forbidden header name that can only be set by the user agent: https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name.

`User-Agent` used to be a forbidden header name, but that later changed (as mentioned in the Note at the bottom of the link above).

Firefox has fixed this (https://bugzilla.mozilla.org/show_bug.cgi?id=1188932), but Chrome has not (https://bugs.chromium.org/p/chromium/issues/detail?id=571722).

Firefox sets the user-agent to `node-XMLHttpRequest` (which is the default https://github.com/driverdan/node-XMLHttpRequest/blob/master/lib/XMLHttpRequest.js#L41). Apparently, this is also setting `Accept-Encoding: gzip,deflate,br`, because Firefox is sending this header already.

However, Chrome insists on setting the user-agent to `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36`. I tried setting this explicitly using a ConnectionInfo object, but Chrome still continued to send the same user-agent.

I assume Chrome will automatically start sending this header once the bug is fixed, so I'm going to close this issue for now. Feel free to reopen it if you think it should still remain open.
