### ISSUE TITLE
Trying to click URL in shorting tooltip

### ISSUE THREAD

**Issue by danuker** [AugurProject/augur#1633]
I see the "Don't think this event is going to happen?" tooltip.

However, I want to click the URL (the one to http://docs.augur.net/#short-position). The tooltip goes away as soon as I move my mouse away from the question mark. I should not have to type it in.

![augur-hover-url](https://user-images.githubusercontent.com/74835/40156775-3b7db89c-59a4-11e8-973c-9282c5aeb619.png)

Also, perhaps this tooltip should go instead to the Trading manual (http://docs.augur.net/#trading). I want to trade, not necessarily to short (I am on the "Buy" tab in the screenshot).

**Comment by sharkcrayon** [comment]
@danuker I agree with you on both those points.

Making it so the user can interact with the content within the tooltip is on our list for after MVP launch.

The location of the tooltip icon isn't ideal, but I'm not sure hiding it on the "Sell" screen makes sense either (since users who don't know how to short wouldn't know to look there anyway). This is also on our list to deal with after MVP launch.

**Comment by danuker** [comment]
Fine by me. To be honest, I'm excited about the launch more than UX details, for now. Hats off!

**Comment by bthaile** [comment]
Looking to fix/correct in future release, closing this issue.

**Comment by danuker** [comment]
@bthaile But isn't the purpose of issues to track what is fixed and what isn't?

**Comment by bthaile** [comment]
Yes, unfortunently we have another internal tracking system. This UX issue will be addressed in future design.
