### ISSUE TITLE
Mobile Trading Page: Outcomes component

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1721]
- [x] update to increase type size of outcome names in rows to 12px and make bold. To give more standout as 'Yes' is getting lost

- [x] Outcome should  be 12px spacing from the top of that row
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4fa086c5-fd26-4130-b69f-413b740c3965)

- [x]  when there is no value so we are showing a dash, can we make this #777 and centre align
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b1b94191-8bf5-4851-be12-db63cae1e9f0)
Otherwise it can look like a minus icon that's linked to the number to the right:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/293dd272-2b60-4255-8629-bda47d6da01b)

**Comment by JohnDanz** [comment]
center align looks a bit off due to the way the page is currently laid out (it's a grid but no gaps so the dashes don't even look like they are in the right columns) -- instead of refactoring the CSS right now I decided to just use some right padding (roughly 3-4 digits worth) to make it clear what column it's still in and I also used a slightly longer dash character (horizontal bar instead of mdash)

<img width="1298" alt="Screen Shot 2019-04-22 at 5 21 25 PM" src="https://user-images.githubusercontent.com/10524630/56536214-1a3d5a80-6523-11e9-94c3-d4fab4333868.png">

<img width="461" alt="Screen Shot 2019-04-22 at 5 22 54 PM" src="https://user-images.githubusercontent.com/10524630/56536283-4b1d8f80-6523-11e9-95b8-a0e359f94d05.png">

**Comment by matt-bullock** [comment]
The longer dash works well. Left alignment is fine for now so let's leave this but maybe centre aligned would work better as the alignment looks further off when there are numbers in the row below:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7cbc9be1-9f13-42cf-9dd5-26071578083e)

Let's leave this for now but is it possible to make the dashes #777777

**Comment by JohnDanz** [comment]
I'm going to update the dash color, but the alignment is a bit more annoying than I thought because of the way this is laid out, I'll look into adjusting to a grid layout to be more consistent with spacing/alignment then we are now where it appears to have padding/margins but actually doesn't.
