### ISSUE TITLE
Mobile - trading pg scrolbar issue

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1722]
When on the trading pg in mobile - weird scrollbars for multiple tags....

see screenshot

![4-18scrollbar.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/6965e79d-ad4e-4825-b72d-bce236d8b4b0)

**Comment by matt-bullock** [comment]
Tags should stack rather than horizontal scroll - this will solve the issue
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b68dace1-6959-4282-bbed-d0035a5ccb53)


8px vertical spacing between tags
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/5d2012c1-16ff-4c8c-b0be-fb45cafa065b)

**Comment by Chwy5** [comment]
the scroll bar is gone - long text is going to the next line but the spacing is still of....

see screenshot - see above for spacing requirements - moving this to 1.14 to be completed

![4-23spacing.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/4d0cf03a-38ee-4a50-b3d4-1ba25c692529)
