### ISSUE TITLE
Mobile Sub Nav amends

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1766]
background: rgba(15, 10, 25, 0.9);
backdrop-filter: blur(2px);/* Note: backdrop-filter has minimal browser support */

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/59c95c87-b028-4e5c-b7b5-d47b84bc95d8)
Height of bar should be 64px, with 90% opacity and background blur if possible

So it looks like this:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ac239dcd-142c-4586-ad64-6c8f51dea7c2)

**Comment by JohnDanz** [comment]
The problem with this is it's going to require a refactor because it's designed to be a hard top. I don't think we should do this during 1.13 and if we are going to do it at all it should be in 1.14. 

The reason I question whether it should be done is that I don't see a point to it if that menu never moves anyway and you can't interact with the content below it. It feels like it's just there because it might look cool? Functionally it doesn't change anything as far as I can tell, in terms of how the app is used. Can we push this to 1.14 and discuss? upping the estimate based on the refactor time we will need.

**Comment by bthaile** [comment]
@Chwy5 the effort for this task is outside of the scope for v1.13 recommend pushing to v1.14 and discuss.
