### ISSUE TITLE
No transactions go thru on firefox or chrome

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#183]
1) Login with account aaaaaa aaaaaa
2) try to do anything
3) your tx will never be included.

**Comment by joeykrug** [comment]
Also happens with new accounts even after they have ether

**Comment by tinybike** [comment]
This happens to me when I use aaaaaa/aaaaaa, but when I created a new account bowser/bowser I was able to use the faucets, then buy shares successfully.  What other username/password combos have you experienced this with?

**Comment by tinybike** [comment]
The problem turned out to be the nonce -- it was off-by-one.  I reset the nonce (to 6, the value it was supposed to have), and right afterward the entire backlog of aaaaaa's transactions flooded out to the network -- guess they were just sitting quietly in geth's txpool this whole time, hehe.

![screenshot - 09212015 - 04 48 22 am](https://cloud.githubusercontent.com/assets/2637020/9991144/3d246e2c-601c-11e5-98cb-d5d9bdfbca51.png)

Putting in a fix now.

**Comment by tinybike** [comment]
Fixed in a7a76a801f63f1a7db3151e2ec47b94e75249475.
