### ISSUE TITLE
augur-node: add end date filter to getMarkets

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#2007]
![image.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/11cff70d-39de-432b-882c-24008869ce0b)

**Comment by ryanberckmans** [comment]
Suggest we implement this fully front end as follows

1. hardcode cut-off date in UI
2. filter markets by hardcoded cut-off date using `market.endTime`

I'm open to a `getMarkets` filter, eg. on endTime, but I think this particular need might be better served doing it fully on the front end.

**Comment by ryanberckmans** [comment]
@andrewdamelio

**Comment by andrewdamelio** [comment]
@ryanberckmans 👍

**Comment by ryanberckmans** [comment]
Per Andy's point we may support this in augur-node if there's an interaction with pagination. Andy will decide

**Comment by andrewdamelio** [comment]
@ryanberckmans Yeah, I think we need to add this to augur-node...  

Otherwise, we will get strange UI behavior,  for example, the total market count (in the pagination label)
<img src="https://user-images.githubusercontent.com/1683736/57165577-83e02300-6dc5-11e9-8c9e-5086273063a4.png" width="333" />
wouldn't be correct since we can't exclude markets past the expire date until we load the marketData.

**Comment by ryanberckmans** [comment]
You got it, will do
