### ISSUE TITLE
Support staking REP from a cold wallet (via smart contract)

### ISSUE THREAD

**Issue by ndorf** [AugurProject/augur#2027]
**Is your feature request related to a problem? Please describe.**
Since REP is meant to be used weekly, it's not super practical to store it in a cold wallet. But, keeping large amounts of it in a hot wallet presents a security risk.

**Describe the solution you'd like**
The MakerDAO voting system uses a solution that could work here. One deposits their tokens in a smart contract, which can perform the token functions (voting for MKR, staking for REP) on behalf of the user, authorized by the hot wallet. But no transfers are possible, except withdrawal back to the cold wallet. See: https://vote.makerdao.com/

**Describe alternatives you've considered**
A hardware wallet is a decent solution for many users, but requires trust in the manufacturer and suppliers. It seems desirable to support a pure software solution as well.

**Comment by pgebheim** [comment]
Thanks for the suggestion!

This would be a cool addition to the augur ecosystem! Since it can function perfectly well as a third party contract, we are currently not likely to implement this ourselves (for v2). But I will add this to a list of desired community contributions.

I think this should be pretty easy for someone to put together. It could be useful either as a REP pool contract or as a contract an individual could deploy to manage their REP staking.

**Comment by joeykrug** [comment]
v2 supports already bam!

**Comment by justinbarry** [comment]
@joeykrug I'm closing this accordingly.
