### ISSUE TITLE
[Roadmap] Cleanup for filters

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#2328]
After this filter release this week we need to do a slight iteration to fix some quirks with it.

- fix 99% spread -> 100% all spreads thing
- add unit tests
- no longer assume there is infinite liquidity at the edges
- Use dynamic text in market creation specific to a given user's market + show ahead of time whether their market will show up with default filters
- show warnings on market pages that fail invalid filter
- tooltip on filters on market page that has similar language as market creation one
- Don't uncheck invalid markets box if someone owns shares of that market. What it should do is keep it filtered and if you go to the portfolio page you can see those markets because they’re in your portfolio
- only show tags and categories based on what markets pass the filter. Rank tags and categories by liquidityTokens of markets within them 
- There’s also the drop down arrow bug where if you click on the filter dropdown arrow it doesn’t actually show the filters

**Comment by ryanberckmans** [comment]
✅ account for TVOM in PR today

**Comment by ryanberckmans** [comment]
Paul asked me to list these new items based on discussion with him, Joey and Chwy

* make sellIncrement smaller so that markets with less liquidity survive spread filter. (Currently sell increment is 0.05 ETH / $12 USD, proposed 0.02 ETH / $4 USD)
* liquidity filter also available as a standalone filter, eg. to sort by OI + liquidity filter
* default homepage caps at 2% fee instead of 5% [requested by chwy, not yet approved by Joey]
* gas prices are currently baked in when order book changes, we might want to apply them in getter so that filtered markets actually use current gas price

Not new, but note on UI+data design already being done:

* "Use dynamic text in market creation specific to a given user's market + show ahead of time whether their market will show up with default filters" --> Cillian, Chwy and Ryan have completed a v2 mockup + data design for this, some of which we might want to backport into v1, and the backend data work applies to both v1 and v2

**Comment by joeykrug** [comment]
Infinite liquidity change is under debate at the moment

@ryanberckmans did you see this change + convo in conf-room?

"It’s really just take the invalid filter revenue minus cost idea, but change revenue to be revenue if the market resolved at the max for the bid and the min for the ask. Only count liquidity in the liquidity score where revenue - cost > 0"

Basically don't count orders where it'd be unprofitable to take them even if the market resolved at the extremes

**Comment by ryanberckmans** [comment]
@joeykrug saw the change + convo in conf-room. Change makes sense!

**Comment by pgebheim** [comment]
I believe this is done with the last commit.

**Comment by pgebheim** [comment]
Re-opening, none of the subtasks for account for...

**Comment by pgebheim** [comment]
@bthaile 

i think this one got done earlier, am I wrong?:
- There’s also the drop down arrow bug where if you click on the filter dropdown arrow it doesn’t actually show the filters

These UI tasks are left (These should be a part of #2366)
- Use dynamic text in market creation specific to a given user's market + show ahead of time whether their market will show up with default filters
- Show warnings on market pages that fail invalid filter
- tooltip on filters on market page that has similar language as market creation one
- Don't uncheck invalid markets box if someone owns shares of that market. What it should do is keep it filtered and if you go to the portfolio page you can see those markets because they’re in your portfolio
