### ISSUE TITLE
Confirm blockhash of most recent blocknumber on startup

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#2677]
To prevent bad data we should confirm the current head block we have data for hasn't been reorganized.

The following needs to be done:
1. Add blockhash to sync status db.
2. Get most recent blocks hash.
3. Compare and execute rollback as before if not a match.

**Comment by pgebheim** [comment]
This is meant to mitigate a very unlikely issue where a client stops getting block updates at some point and then there is shortly after a very long re-org that puts their local view of the world out of sync with the chain.

Currently we always roll back 5 blocks from our last max block and then re-sync. It's easy to make that number bigger and decrease the chance this error happens, so im going to close this issue for now since it's not needed to keep things working.
