### ISSUE TITLE
Fix Volume calculations

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#289]
Currently the volume calculations in Augur Node are done by taking the trade amount multiplied by the trade price and summing that with previous volume.

Instead when we update the volumetrics we should increase overall volume by:

- (The lowest of makerSharesProvided and takerSharesProvided) * numTicks
- makerTokensProvided
- takerTokensProvided

The actual log data will use the terms:

numCreatorShares
numCreatorTokens
numFillerShares
numFillerTokens

**Comment by joeykrug** [comment]
Shouldn't this actually be data from https://github.com/AugurProject/augur-core/blob/master/source/contracts/trading/FillOrder.sol#L397 so:

Instead when we update the volumetrics we should increase overall volume by:

(The lowest of makerSharesDepleted and takerSharesDepleted) * numTicks
makerTokensDepleted
takerTokensDepleted

Basically using the amounts that actually got "depleted" / filled instead of the amounts provided (which may not necessarily get used in a trade)?

**Comment by nuevoalex** [comment]
The actual log data will use the terms:

- numCreatorShares
- numCreatorTokens
- numFillerShares
- numFillerTokens
