### ISSUE TITLE
Allow users to "slash rep" to report colluding

### ISSUE THREAD

**Issue by niran** [AugurProject/augur#31]
From #23:

If someone tries to collude during the first half, and you can provide their salt and report and address to the network, you get their rep (because they are a cheater)!
Send a transaction to `def slashRep(branch, votePeriod, salt, report:arr, reporter)` to do this.

**Comment by tinybike** [comment]
Added this to the augur.js API in AugurProject/augur.js@8df7c965e47766daa99a60a6767c8613144ef5c2.  (This particular function seems to be working, in spite of the recent ABI issues!)

**Comment by thinkloop** [comment]
should this still be open

**Comment by joeykrug** [comment]
Branch salt report reporter event are the params now but yes, this still isn't done as far as I know

**Comment by tinybike** [comment]
@joeykrug: would you mind walking through exactly how this works / when users would use this?

**Comment by joeykrug** [comment]
To report collusion. If someone tries to collude during the first half of a period, and you can provide their salt, report, address, event they colluded on, and branch to the network, you get half their rep (because they're attempting to collude/cheat).  The other half goes to the regular redistribution pool.

```# Anti cheat/collusion mechanism: provide ballot and random salt to steal rep from a colluder
# Returns:
    # 0: not a valid claim
    # -2: past reveal date
    # -3: reporter being slashed doesn't exist
def slashRep(branch, salt, report, reporter, eventID, testing)```

Testing should be 0 on the actual network, was a flag i've been using to make tests easier

**Comment by tinybike** [comment]
Moved to CH
