### ISSUE TITLE
Make markets clickable

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#313]
https://www.reddit.com/r/Augur/comments/46jvbq/make_markets_clickable/

**Comment by tinybike** [comment]
As you will be able to see when our nodes are back online, this was added in e31359b92b4146495b69e1d239b69bcad779783c :)

**Comment by Newportkiwi** [comment]
Just something to remember - we have numerous market lists (the markets page, portfolio pages, my markets, reporting pages etc.). We should try to keep behaviour across these lists as similar as possible - it can get confusing otherwise. 

For example, clicking the market on the Markets page takes user to the trading screen. Does clicking the market on the My Markets page do the same thing? Or should it take them to the summary page to see how many fees they've earned etc. 

One of the main reasons I used buttons was to highlight to the user what the main function is that's available on a particular list (and to use combo buttons when there are multiple functions).

We can see how this goes (there are no other lists in place right now anyway) but just be careful about making what seem like simple changes - they often have knock-on effects.

**Comment by joeykrug** [comment]
IMO it should go to "the markets page" that has all the information about the market, i.e. https://app.augur.net/markets/-133fc7fe6a890b62b6d7d76e497fecd09e1355403a166905105d949c99429725

![marketspage](https://cloud.githubusercontent.com/assets/5925937/13258165/ab7681ba-da17-11e5-924b-25990d0ac22d.PNG)

**Comment by tinybike** [comment]
Right now it goes to the Trade page (the one with the details Joey posted a screenshot for) if you're on the Markets or My Markets pages, and it goes to the market's Report page if you're on the Reporting page.  This seems like reasonable behavior to me, but if you guys prefer something else, I'm open to changing it.

**Comment by tinybike** [comment]
It also goes to the Trade page if you're on Portfolio.
