### ISSUE TITLE
Market odds wrong

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#325]
![wrong](https://cloud.githubusercontent.com/assets/5925937/13297150/79e9bfc4-daf6-11e5-8862-1828517087d8.PNG)

**Comment by joeykrug** [comment]
buying 1 share of hillary when bernie has 10+ more shares shouldn't make Hillary's odds go up to 99.8%

**Comment by tinybike** [comment]
I think this was caused by market outcomes being passed to augur.js out-of-order, and augur.js naively using the outcome's array index.  As of AugurProject/augur.js@4d946e0c6eec89595b45a6d14013e59f2fdc3973, augur.js's `price` method now matches the outcome `id` field explicitly, which should solve this issue.
