### ISSUE TITLE
Replace call to augur.getTimestamp on new block

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#3391]
If time controlled use TimeStampSet logs If normal, use timestamp on the block.

https://github.com/AugurProject/augur/blob/18f0fdd7f053a45f969aafb553b9dd00022c1e2d/packages/augur-sdk/src/state/Controller.ts#L56

**Comment by justinbarry** [comment]
The coordination of timestamp and block info needs to be centralized. If a getter is concerned with new block the passed block should have the "correct" timestamp.

**Comment by pgebheim** [comment]
This still seems like an issue which is potentially concerning since we'll be doing getTimestamps in getters.

![image.png](https://images.zenhubusercontent.com/56019653638e718c995d3fc0/2d8f3efd-efce-474b-93ca-9bc6b922cb18)

@nuevoalex @justinbarry  -- Do you think this is an important issue before v2 launch for stability?

**Comment by joeykrug** [comment]
Status?

**Comment by robert-e-davidson3** [comment]
This still needs to be done.

From `augur.ts`:
```
async getTimestamp(): Promise<BigNumber> {
    return this.contracts.augur.getTimestamp_();
}
```

**Comment by pgebheim** [comment]
@robert-e-davidson3 -- Is this handled by your branch?
