### ISSUE TITLE
image uploaded in new market creation, but image displays broken image 

### ISSUE THREAD

**Issue by RonB7139** [AugurProject/augur#351]
suggest explain text about recco size of image, as well as limits

**Comment by tinybike** [comment]
Yes, I've been struggling to get image display working correctly for a few days now.  Agree that this is important.

**Comment by pqdeep** [comment]
confirmed
created "Will Iran test detonate a nuclear bomb..." but image didn't appear:
https://app.augur.net/markets/-9623bbd75f40501c3774a898a48b13e103da7b0eaa2d9987206a80b39dbdfa61

**Comment by tinybike** [comment]
Yes, this isn't a browser-specific issue; I'm experiencing it at as well.  Working on it.

**Comment by tinybike** [comment]
Fixed in 50f2bda952b7d0fa121dc9dae0f5bc6b1c5a49b7 / AugurProject/ramble@beb661a81d85ee7ef2b7474d683b76f5da371d69.  (The only image that isn't working now, as far as I can tell, is the only one that was working before -- the SpaceX market -- b/c it was encoded slightly incorrectly.  I opted not to include hacks to make that one image keep displaying...)
