### ISSUE TITLE
Improve error message when Ethereum node returns current block # earlier than most recent block

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#359]
We should display the following error message when the current block is < the max block synced, or when the current block - max block synced is < 105:

```The connected ethereum node is reporting a current block number which is earlier than the most recent block that has already been synced. Please wait for the ethereum node to become fully synced, or change to a different node.```

Currently, the message looks like:

```Not enough blocks to start blockstream reliably, wait at least 105 from 6711485. Current Block: 6698618```

Also, the check of: 

`current block - max block synced is < 105`

is wrong. Instead, this should be checking if:

`current block - max block synced is < 5`

**Comment by pgebheim** [comment]
@adrake33 It looks like this is still open:

https://github.com/AugurProject/augur/blob/2d006f8b1cafd66d29d6c631e41ab35ecc209c84/packages/augur-node/src/blockchain/bulk-sync-augur-node-with-blockchain.ts#L43

@epheph You agree with my error text?

**Comment by epheph** [comment]
The text isn't quite accurate. If the node is at say block 100, and last sync stopped at block 98, the error message would still occur, because we want to have a few blocks between in order to deal with re-orgs (since we currently rely on blockstream having the transactions in memory to rewind). I will write some better text (and you are right, the 105 vs 5 thing is a problem and has already been fixed)

**Comment by epheph** [comment]
https://github.com/AugurProject/augur-node/pull/759/
