### ISSUE TITLE
For categorical markets, we should impose an "other" option by default during the market creation process.

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#368]

**Comment by Newportkiwi** [comment]
Do all multiple-choice markets need this option? 

What will be the result of Barcelona vs. Real Madrid: Barcelona win, Madrid win, draw? As an example.

**Comment by tinybike** [comment]
All multiple-choice markets do **not** need this option, and we should not be imposing this on people, IMO.

**Comment by Newportkiwi** [comment]
I have some reminder text about this in the new market creation pages - hopefully people read and it follow the advice.

**Comment by pqdeep** [comment]
Hope so - there's often an "other" option that many people don't foresee. Alternate suggestion: include a pre-filled (opt-in) "Other" field that users are free to delete. Anything that could help reduce/eliminate ambiguous outcome workloads on reporters.

**Comment by Newportkiwi** [comment]
Hhhmmm, maybe it's not such a bad idea. An "Any Other Outcome" tacked onto the end of all multi-choice markets will ensure every possible result is covered. Even in markets where an "any other option" isn't immediately obvious it could be useful.

For example, the soccer game I mentioned above. Maybe it gets called off due to the stadium lights failing, or a flash flood carries away the road to the stadium. 

Maybe this is a "better safe than sorry" situation we can at least test for a while?

**Comment by pqdeep** [comment]
Not urgent for beta, but should be considered for live
