### ISSUE TITLE
Testing improvements

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#3684]
Problem
==

Integration testing getters is slow and at times inconsistent.

Road to a Solution
==

1. Isolate state between individual tests in the same suite (#3683)
2. Find commonly used state amongst tests
3. Build a pre-computed state mechanism
4. Alter tests to reconstitute state vs rebuilding every time

**Comment by robert-e-davidson3** [comment]
Some remarks:

> 2. Find commonly used state amongst tests

Some states that come to mind:
1. Just deployment and contract registrations. Possibly also Cash authorizations for users. A few tests will want to use this state to keep verification simple.
2. A kitchen sink of a few kinds of each market, with different sets of orders and the like. Most tests can use this.
3. The contract ecosystem in the dispute/forking state. A couple of tests would use this.
4. A post-fork kitchen sink, for when we need there to be universes with children. Possibly several forks in. However, this might not be useful since we currently don't have any tests for this state at all.

With the seed forking, each of these build off of eachother so it's efficient.

> 3. Build a pre-computed state mechanism

Mostly we need a way to get ahold of this pre-computed state, like market addresses. They could be in the seed itself.

> 4. Alter tests to reconstitute state vs rebuilding every time

Making this work cleanly will be quite the task but it will overall lead to faster and more reliable tests.
