### ISSUE TITLE
Update Getter tests to use precomputed states

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#3740]

**Comment by joeykrug** [comment]
what's this mean?

**Comment by robert-e-davidson3** [comment]
Probably this means expanding on how we use ganache seeds. Right now we just use one seed that contains the deployed contracts. But we could have more seeds that contain other commonly-needed state like markets, on-chain orders, forking or forked state, etc.

We could also build these seeds during our regular build process and commit them to augur-artifacts so that when we run tests, the loadup time to create the seeds will be done once whenever the contracts change. There should be another ticket for thithat though.
