### ISSUE TITLE
Update Augur whitepaper with v2 changes

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#394]

**Comment by Austin-Williams** [comment]
This is a WIP and will be updated as things are completed/decided.

## Changes to include

- [x] DAI instead of ETH will be used for unit of account
- [x] REMOVE section about `numticks` (not needed anymore since Invalid will be explicit)
- [x] Use it or lose it
- [x] Remove 5% early migration bonus and computations that use it
- [x] Recompute security multiplier due to use it or lose it
- [x] Invalid as an explicit outcome
- [x] Remove appendix section detailing the major changes between versions
- [x] "Scenarios" can be removed ~~or adjusted~~
- [x] DR reporting time reduced from 3 days to 1 day (not including flow chart update)
- [x] Continuous dispute rounds (not including flow chart update)
- [x] Update flow chart to incorporate continuous dispute rounds and a 1 day DR window.
- [x] Burning 20% of losing dispute stake (requires changes to proofs in appendix). Also change "50% ROI" to "40% ROI" where applicable.
- [x] Update "Potential Issues and Risks" because v2 changes change/eliminate some of the listed risks
- [x] ERC777 support (REP, shares, and PTs to be ERC777 tokens)
- [x] "Creator fee" is the max of "initial report bond" and "no-show bond"
- [x] "Fast Resolution" (first dispute round is 24 hours)

## Other possible changes to include (depends on whether they are accepted)

- [ ] Max duration on markets
- [ ] Changes to the price oracle
- [ ] ~Variable creator bond (allows creator to post higher than necessary bond)~
- [ ] ~Buyback & burn~

**Comment by pgebheim** [comment]
@Austin-Williams -- Any updates on this that need to be noted in the ticket?

**Comment by Austin-Williams** [comment]
@pgebheim  -- Nothing noteworthy. I'm just working my way down that list (and occasionally adding things to it as needed).

**Comment by pgebheim** [comment]
@Austin-Williams -- is this draft in Google Docs or are you doing this in a fancy academic paper editor with LaTeX support?

**Comment by Austin-Williams** [comment]
@pgebheim -- I'm writing it in LaTex, using Overleaf. I basically just forked the v1 white paper and have been modifying that. Heres a [link to the doc on Overleaf](https://www.overleaf.com/read/kpxfzvhxkhrv).

**Comment by pgebheim** [comment]
Fancy! Thanks for the link

Paul
paul@augur.net

________________________________

**Comment by MicahZoltu** [comment]
> "Creator fee"

I'm not a fan of calling it a "fee" when you get it back if all goes well.  I very much prefer "bond" for such things.

**Comment by MicahZoltu** [comment]
On the flow chart, it goes from initial report to dispute round, but I believe it is more accurate to have it go to "waiting for next fee window to begin".  Also, the flow chart currently doesn't capture that rounds can iterate instantly up to a threshold.

**Comment by Austin-Williams** [comment]
> Also, the flow chart currently doesn't capture that rounds can iterate instantly up to a threshold.

I think it does. If the slowdown threshold has not been reached then the next dispute round starts immediately. So, for example, several dispute rounds can complete in a single transaction.

**Comment by MicahZoltu** [comment]
Ah, I see.  In that case the "Dispute Round" box text is incorrect, the disputer round can last as long as 14 days for fast rounds, 7 days for slow rounds.

**Comment by Austin-Williams** [comment]
IIUC, each round (whether fast or slow) can last at most 7 days.
Fast rounds can end ~instantly, and slow rounds last exactly 7 days.

**Comment by MicahZoltu** [comment]
I don't believe that is correct.  Each round (fast or slow) must survive a full dispute window without anyone filling the pot in order for it to finalize.  Fast disputes just mean that as soon as round `n` is filled, filling of round `n+1` can start.  Slow mode functions just like now, where a market will go dormant when it fills until the next round starts.

**Comment by Austin-Williams** [comment]
> Each round (fast or slow) must survive a full dispute window without anyone filling the pot in order for it to finalize.

So for fast dispute rounds it's "must survive a full dispute window" and not "must survive any 7 days in a row"?

**Comment by MicahZoltu** [comment]
Correct, as I understand it.  Would be good to have @nuevoalex chime in, but I'm about 80% confident in that.

**Comment by nuevoalex** [comment]
That is correct. For a market to resolve it must last through a dispute window with no dispute
