### ISSUE TITLE
Forking: getUniverseChildren gives usersRep as 0

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4067]
condition: user did migrated REP to winning universe during fork. After the fork resolves:

The user should get `migrate market` or `report and migrate` button to migrate markets. 

confirm the user has REP balance on winning universe
```
await AugurSDK.contracts.universeFromAddress("0xa106d7AEB57791D744D468538448a1CFe53b1fC6").getReputationToken_()

(await AugurSDK.contracts.reputationTokenFromAddress("<winning universe rep contract>").balanceOf_("<user account")).toString()
```

The `getUniverseChildren` getter show usersRep balance as 0;.

got more information:
added console.logs to `getUserRep` in Universe.ts
user's child universe balance is correct first time the getter `getUniverseChildren` is called. The second time it's called and subsequent times user's rep balance on child universe is zero.

to repro:

1. make sure there is markets in pre-reporting at time of fork.
2. put app in forking state
3. migrate REP to an outcome
4. push time past fork time
5. finalize the forking market 
6. check user's REP balance on winning child universe
`state.universe.children` in web console
7. migrate a pre-reporting market.
8. check user's REP balance

**Comment by robert-e-davidson3** [comment]
Were the logs received and the db synced after migrating?

This case is handled in the test of the getUniverseChildren getter: it does a fork and `repToken.migrateOutByPayout` then verifies that the `usersRep` field is equal to the amount that was migrated over.

**Comment by bthaile** [comment]
Yes, it was synced after migrating. even migrated a few markets and called the getter a few time by logging out and back in. 

also got tokensMinted logs saying the user got REP, which I called the getter and usersRep was '0'

**Comment by robert-e-davidson3** [comment]
Ah the UI is doing `Market.migrateThroughOneFork` and I'm doing the migration from the rep token itself via `migrateOutByPayout`. Must be an important difference there.

Something strange here is that the getter is using TokenBalanceChanged, which is logged whenever TokensMinted is logged.

**Comment by robert-e-davidson3** [comment]
I edited the automated test of this getter to include this scenario but I couldn't reproduce this bug. Here're the steps my test takes:

1. Faucet REP to user.
2. Create a market.
3. Fork the market by having the user `contribute` REP on different outcomes each round.
4. Migrate enough REP to the new universe that the fork resolves. Has to be done twice due to a contracts bug.
5. Verify the results of `getUniverseChildren`.

Here's the PR (draft) of the changes: <https://github.com/AugurProject/augur/pull/4091>

Am I missing anything?

**Comment by robert-e-davidson3** [comment]
I ran through the repro steps on the UI and couldn't reproduce.

**Comment by robert-e-davidson3** [comment]
This might also be due to Kovan not having been deployed for some time. We deployed to Kovan at about 8:30am October 3rd but the code to get the correct usersRep went in around 2:30pm that day.

kovan deploy:
```
commit 70566631b648b86b827a17fe185c7d72151db68c
Author: Peter Hicks <petong@jah.net>
Date:   Thu Oct 3 08:37:16 2019 -0700
```

usersRep change (https://github.com/AugurProject/augur/pull/4026):
```
commit 4b7214175b847e0035b81857375ef66627db0b28
Merge: 2b0ca0df1d 0c55e2aef4
Author: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
Date:   Thu Oct 3 21:30:44 2019 +0000
```

When we redeploy Kovan, we should retest this.

**Comment by pgebheim** [comment]
Closing per @robert-e-davidson3
