### ISSUE TITLE
Current loading screen a bit bland

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#417]
Perhaps use something like this
![space_background_720](https://cloud.githubusercontent.com/assets/5925937/13653100/52dc46c0-e615-11e5-97ff-030c835c3e57.png)
with the loading tips from here: https://www.google.com/design/spec/patterns/loading-images.html# to make it more interesting

**Comment by tyche78** [comment]
It is obviously not a top priority, but I agree this would tremendously improve the overall UI feel.
Two (lazy) suggestions (I am not a developer):
1- The center circle gradually fills up with a color depending on actual loading progress. Probably harder to implement than a simple cycling .gif though.
2- Small beads of "light" travel from the edges of the pyramid towards the center circle, which glows in a synchronized way. Cycling .gif, with no actual link to the loading process.
Ideally, for far off into the future: a mix between the two

**Comment by thinkloop** [comment]
Loading _screens_ in general are not great ui. They create a strong aura of slowness and hurt pagerank (if that matters). It's much more effective to load the portions of the ui that we can (navbar, page header, buttons, etc.) and have sectional loading animations for the parts that aren't in yet. By the time the user notices the page hasn't loaded, often it will have loaded. Additionally, they can do stuff before loading completes, like click on reporting because that's where they really wanted to go, or manage their account, which does not depend on markets being loaded. Finally, this allows us to stagger loading of elements as the ui becomes more complex - for example we might have a sidebar that requires some sort of loading independent of the markets loading - no reason to have the user wait for the slowest-common-denominator.

**Comment by tyche78** [comment]
Fair point. An animation would be great for the unloaded parts of the screen you mention, though.

**Comment by joeykrug** [comment]
Well... You already have a loading screen, so may as well swap it in with something beautiful haha

**Comment by joeykrug** [comment]
Swap it out*

**Comment by thinkloop** [comment]
If implementation time was less for the sectional loaders would you be up
for it?
On Mar 10, 2016 12:21 PM, "Joseph Krug" <notifications@github.com> wrote:

Swap it out*

—
Reply to this email directly or view it on GitHub
<https://github.com/AugurProject/augur/issues/417#issuecomment-194964672>.

**Comment by tinybike** [comment]
I think sectional loaders are a great idea.  The only time we have a
loading screen is at the very start before the markets are loaded.

**Comment by joeykrug** [comment]
Sectional loaders would be fine if you can get them done before beta launch, otherwise this is just a quick swap out of the current blase background image for the new one above until then

**Comment by tinybike** [comment]
I was thinking sectional loaders not as replacement for the loading screen,
but for parts that already load in sections (e.g. metadata, comments) and
currently are just unpopulated prior to the data coming in.  Doesn't have
to be done for beta!  Just would be nice to have.

**Comment by joeykrug** [comment]
![loading](https://cloud.githubusercontent.com/assets/5925937/13680810/cf8ca548-e6bf-11e5-8567-46116d6a3479.PNG)

Is what I'm talking about swapping out, I don't imagine it'd take more than 10 minutes.  It doesn't jibe with the rest of the UI and isn't a very appealing thing to see when you first visit the beta.  I even provided an image to replace it with

**Comment by joeykrug** [comment]
nice!

**Comment by joeykrug** [comment]
this is way better

**Comment by thinkloop** [comment]
:-)

**Comment by tinybike** [comment]
+1 love it
