### ISSUE TITLE
Add actual gas costs to transaction display

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#428]
Currently the transactions display has estimated (but not actual) gas fees displayed for transactions loaded from logs.  Now that we have augur-node, it should be straightforward for the augur-node to store the gas costs along with the transactions.
...

Good call.
 -pgebheim
...

@epheph We still need to do this correct?
 -sharkcrayon
...

eth_getLogs does NOT store other receipt information, like gasUse or gasPrice.

It's possible to use transactionHash to look up gasPrice (in getTransaction) and gasUsed (in getTransactionReceipt), but that it is 2 more calls for every log we process, and would add decently to sync time.

Do we want to do this for every incoming log? Or just a subset?
 -epheph
...

@epheph I think it might have to be for every log? Can you give an example of how a subset might work?
 -adrake33
...

@serena Please discuss this more with chwy. He has some ideas.
 -adrake33
...

@chwy  what are your thoughts on this? 
 -sharkcrayon
...

IF Augur switches to a stable coin, how will showing the fees work? Will it still be in Eth?
 -Chwy5
...

Gas fees would still be in eth, yes.
 -pgebheim

**Comment by epheph** [comment]
This issue is a little weird for a lot of different reasons:
1.) A log comes from a transaction, and only part of the event that lead to that log came from that transaction's gas usage. This is especially problematic if the user creates a contract which does two things at once (or uses something like DSProxy). 
     - Even augur-native contracts have problems, like if you match 2 orders. Both orders will appear to take the full gas usage for the entire TX
2.) The transaction details don't come from the the getLogs, so a single getLogs that fetches 10 logs that came from, say, 6 tx would require 6 individual TX to look up those tx details.
    - This is especially problematic when using a light-node


If i were going to implement this, I would just add the gas usage info directly to transactionHashes table, then join to that table, instead of baking the cost directly into each individual table.
