### ISSUE TITLE
many calls to `getUserTradingPositions` and `getProfitLossSummary`

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4383]
these calls are part of start up and take time to preform, need to minimize them to give the user impression of a speedy load.

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/e8b85d73-f3c7-4f8b-9e2c-2a0cd956ab2f)

**Comment by joeykrug** [comment]
important for launch imo, all these sorts of things decrease scalability

**Comment by robert-e-davidson3** [comment]
I assume you've got a ton of data to process or are talking to a node like geth instead of ganache because in the `:getProfitLoss & getProfitLossSummary` test I'm seeing very fast speeds:

```
 console.time ../augur-sdk/build/state/getter/Router.js:53
    getter: getProfitLoss called at 1580192171461: 55ms

  console.time ../augur-sdk/build/state/getter/Router.js:53
    getter: getProfitLossSummary called at 1580192171520: 65ms
```

With timestamp caching the times are even faster. I counted 2 contract calls in the summary and at least 1 in getProfitLoss. All getTimestamp calls. So that should just be one uncached call in total after caching:
```
console.time ../augur-sdk/build/state/getter/Router.js:53
    getter: getProfitLoss called at 1580190618325: 38ms

  console.time ../augur-sdk/build/state/getter/Router.js:53
    getter: getProfitLossSummary called at 1580190618368: 25ms
```
(Also I re-ran the uncached version and got a max difference of 2ms.)

There are a few other contract calls than just getTimestamp. I didn't test getters with those calls though.

Need to retest in a more realistic scenario and more of the getters. Some of the other calls might be replaceable with database queries or caching.

**Comment by bthaile** [comment]
this has been addressed with new aggregated getters. it can be closed.

**Comment by pgebheim** [comment]
Thanks @bthaile
