### ISSUE TITLE
Ugly

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#439]
![ugly](https://cloud.githubusercontent.com/assets/5925937/13712316/9b482ee6-e788-11e5-8d22-c170b099ebb3.PNG)

**Comment by joeykrug** [comment]
on desktop full screen --- haven't seen this before

**Comment by RonB7139** [comment]
conventionally a stop order is a market order triggered by when a certain price is achieved...how that price is achieved is a business rule..a stop can be triggered by a quote or by an actual trade (see attached)

a stop limit order is the same but has a max limit on what will be paid, then it should become a resting order
![stop](https://cloud.githubusercontent.com/assets/16419551/13712472/c99281b2-e791-11e5-880c-3a714bb84aef.png)
....because of the way LS LSMR works, this means user will pay 99.999 if they have the funds to do so to cover, which may mean all available funds in user acct
---will there be an FAQ to explain how this works? (any FAQ for beta?)
**FAQ's can use a beta test as well**
---is it desirable functionality to offer for beta?

**Comment by joeykrug** [comment]
This UI has a stop order with the option to make it a stop limit order if you put in a limit price.  I'm not sure how those comments are relevant to the display being ugly though/this issue, they would probably be nice things to have on an FAQ however.

It's supposed to look like this:

![stop](https://cloud.githubusercontent.com/assets/5925937/13712632/588834b4-e78a-11e5-83a7-16cb712b8653.PNG)

**Comment by RonB7139** [comment]
got it...new issue created re: FAQ's

**Comment by thinkloop** [comment]
I believe @Newportkiwi is in the process of designing an overhaul of this page

**Comment by joeykrug** [comment]
it's still a bug though.  Scroll up and look at the top image.  then look at the bottom image how it used to be 12 hours ago

**Comment by joeykrug** [comment]
top image is all messed up --- same device, same browser, windows 10, no changes other than one is on dev site

**Comment by tinybike** [comment]
Obsoleted by 59f966ae8b6d24f221fec1ec166e75a53216429e.
