### ISSUE TITLE
Allow staking more validity bond in V2 contracts

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#463]

**Comment by epheph** [comment]
This changed recently with https://github.com/AugurProject/augur/pull/767 , since it is no longer possible to just forward more ether with market creation.
Now, it will need to either be a new argument to createMarket and a function call to deposit more validity bond after market creation. It's possible only the latter is sufficient, but if the prior is easy, might as well add it.

**Comment by cillianhunter0** [comment]
@pgebheim what is this feature?

**Comment by pgebheim** [comment]
@nuevoalex -- Any idea what this means?

**Comment by epheph** [comment]
In v1, including ether along with the createMarket call would allow you to stake MORE validity bond than necessary. With the move away from ether, that would need to become a calldata argument.

**Comment by pgebheim** [comment]
I don't think this was meant to be a contract task, I think this was probably meant to be some sort of UI task that would allow people to do this. I don't think this really makes that much product sense?

@cillianhunter0

**Comment by epheph** [comment]
The idea was that users might stake more validity bond to convince users their market would resolve valid. If it was to be a part of market creation, it would require a change to v2 contracts.

That said, this ticket is ancient and before massive changes to validity. I'm just hoping to provide historical context since i remembered this one.

**Comment by pgebheim** [comment]
Thank you for doing so :)

That context does help a lot!

Paul
paul@augur.net

________________________________

**Comment by joeykrug** [comment]
Still relevant I believe

**Comment by pgebheim** [comment]
@joeykrug -- This doesn't appear to be a part of the market creation flows as is.

Should we consider this for an addition? Currently none of the visibility code uses this value as any sort of signal.

@cillianhunter0 @matt-bullock @Chwy5 -- Thoughts?

If we're not gonna do it I would love to get the issue closed / added to design backlog.

**Comment by Chwy5** [comment]
Not sure this is needed...

Can just as easy place an invalid market offer on the book

**Comment by joeykrug** [comment]
not needed
