### ISSUE TITLE
Provide GraphQL endpoint in Augur Node

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#495]

**Comment by joeykrug** [comment]
dupe, mentioned in another issue

**Comment by adrake33** [comment]
This is actually a separate issue from #402. The plan is to create GraphQL endpoints in AN (which is this task), and then transition to using these throughout the codebase over time. #402 is to update the existing API endpoints to call the GraphQL endpoints created by this task.

**Comment by pgebheim** [comment]
This may be a good issue to spike quickly once the AN2 structure is set up.

@nuevoalex or @epheph -- thoughts?

**Comment by epheph** [comment]
Ya, a 2-person spike on this is probably good to make sure the approach is well-structured

**Comment by joeykrug** [comment]
Why not just create and use endpoints at the same time to phase them in while making sure the tests continue to pass?

**Comment by adrake33** [comment]
@joeykrug We aren't entirely certain if we'll be able to use GraphQL for all of our needs, so I believe the idea was to create the GraphQL endpoints, do some initial testing, and then start calling GraphQL from the existing endpoints, do some more testing, and phase them in in this manner, so that it would be fairly easy to drop GraphQL if need be.

**Comment by pgebheim** [comment]
I'm removing this from V2 as we aren't targetting it for now.

Leaving in Backlog.

**Comment by bthaile** [comment]
@pgebheim said close this
