### ISSUE TITLE
Can create your own "fake" markets with fake Augur & Universe

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#4971]
**Describe the bug**

It's possible to pass in your own custom _augur and _universe to MarketFactory.createMarket and generate a market contract that is "fake". I don't see any way to cause damage with this, since it isn't created by universe it is never considered a real market, and it has no privileged access and does not emit any events that would be misleading.

Might be a wontfix

**Comment by MicahZoltu** [comment]
At least back in v1, this was "by design".  Augur didn't make any claims about which deployed universe was the "legit" one and which was not, since it didn't want to give any preference to FF genesis universe.  Thus, the contracts just validate that they correlate with each other, but not that they correlate with some particular anchor.

**Comment by epheph** [comment]
~~Although in the universe case, specifically, that is no longer the case. you cannot have non-"official" universes. but the point still stands, people can generate meaningless contracts from the official contracts.~~

~~They're all still governed by REP holders, but no more creating secondary genesis universes.~~

You can go straight to the factory to create your own non-integrated universes.

**Comment by epheph** [comment]
Anyway, i haven't found a method for this to be a larger issue, so it's just a "known issue" (like last time)
