### ISSUE TITLE
Can register unsafe GnosisSafe for other users

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#4975]
The GnosisSafeRegistry register() here:

https://github.com/AugurProject/augur/blob/67c0fec95e65fca8d27751f28a6c06e5247978c6/packages/augur-core/source/contracts/GnosisSafeRegistry.sol#L52

trusts the safe, likely because it confirmed that the hash of the deployed bytecode and master copy matches. That is not secure, consider the following actions

User A creates their own real GnosisSafe (we'll call it safe X)
User A asks safe X to give approval to User A for every token they can think of
User A then calls safe X and requests it perform a DELEGATECALL into a new contract which
     1.) Updates the storage to set the ownership to User B
     2.) Calls into GnosisSafeRegistry.register()

User B now has a GnosisSafe which they would believe to be safe, they fully control, and is now the GnosisSafe returned by the GnosisSafeRegistry, but any assets held by that safe could be taken by User A

**Comment by nuevoalex** [comment]
Relevant GH issue for their contracts here: https://github.com/gnosis/safe-contracts/issues/141

**Comment by MicahZoltu** [comment]
You can do worse than just approving yourself.  You can also set yourself as a shadow-owner of the safe and thus have complete control over it.

It is unclear to me how the solution proposed in the linked thread actually addresses this, at least not as described.  I believe you would need to have the `IProxyCreationCallback.callback` you write (presumably just a renamed `GnosisSafeRegistry.register()` function) ensure that `msg.sender == proxyFactory` as well as validating that `initializer` is empty.  It is worth noting that such a change will make it so `ProxyFactory` cannot change without also changing `GnosisSafeRegistry` since its address would be baked into the `GnosisSafeRegistry` as an "implicitly trusted caller of registry contract".  Also if `ProxyFactory` is updated in the future, it needs to be ensured that it is not possible to execute any arbitrary calls through it, as that would allow an attacker to fake a `.proxyCallback` call from the trusted `ProxyFactory`.

This change would also mean that users would not be able to bring their own Gnosis Safe to Augur, they **MUST** use a Gnosis Safe created through Augur directly, since any other Gnosis Safe would not be registered and not be able to be registered.  This may not be an issue if you weren't planning on supporting externally created Gnosis Safes anyway, though that feels a bit lame in terms of ecosystem interoperability.

**Comment by nuevoalex** [comment]
@MicahZoltu all of those conditions you mentioned are already the case in the codebase
