### ISSUE TITLE
Drift on rep price oracle if not calculated frequently enough

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#4990]
https://github.com/AugurProject/augur/blob/8640bc720b02d9b616a6d52a9f468fc7f4e8c6fe/packages/augur-core/source/contracts/reporting/RepPriceOracle.sol#L91

If getWeight ends up capping values > 1e18 to = 1e18, the price will drift and never recover (since all price modifications apply deltas to existing price).

Need to make sure `calculateNewExchangeData` is called more often than `tau` blocks 
```
    uint256 public tau = 1 days / 15; // The time period (in blocks) of the twa, assuming a block is mined every 15 seconds. TODO: Review this value
```

**Comment by epheph** [comment]
There will also always be price drift between genesisInitialRepPriceinAttoCash and actual initial liquidity?

What if first liquidity provider sets the initial liquidity point like this:

REP: 1e18
ETH: 1e9

Or what about the other way?

REP: 1e9
ETH: 1e18

**Comment by nuevoalex** [comment]
I'm not sure it could be described as never recovering exactly as much as resetting the baseline for the average. It doesn't really apply a delta to the existing price (this is probably a misunderstanding because of my horrible variable names). Assuming the cap were reached it would simply only consider the timeline of reserves going back tau blocks in calculating the average.

There will be price drift between the genesis initial value for sure. Though for it to impact it greatly the initial price would need to be far off reality or the Uniswap oracle would need to be manipulated for a sufficient period of time as is always the case.
