### ISSUE TITLE
CompleteSetsPurchased event not always emitted

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#4992]
https://github.com/AugurProject/augur/blob/67c0fec95e65fca8d27751f28a6c06e5247978c6/packages/augur-core/source/contracts/reporting/ShareToken.sol#L109

There are two entrypoints to the internal buyCompleteSetsInternal . Only one of them emits the augur log for "CompleteSetsPurchased". (they both emit the OI change event)

**Comment by epheph** [comment]
Same with "sellCompleteSets" vs "publicSellCompleteSets" . It almost seems like the non-public version of these used to be internal? It even gets the universe to do nothing with it, when the only reasonable thing for it to use a universe for is to emit a log

**Comment by nuevoalex** [comment]
Yea this is intentional. This is somewhat confusing and occurred as a side effect of making the trading contracts external to the core deployment. The intention is for the "public" variants to be used in cases where someone or a developer wants the log emitted. The use case is for exposing this as an actual explicit user action.

The non "public" variants exist to be used in the context of application development and would be called by other contracts however, usually in the process of facilitating a trade. The complete set purchased log events in that context would largely be gas wasters and would require developers looking at these events for the above case to write code to ignore them.

**Comment by epheph** [comment]
And these missing complete sets events won't be a problem to the ETL middleware? (i haven't looked at any of that stuff yet)

OK, i'll make note to drop query for universe in the non-logged path

**Comment by nuevoalex** [comment]
Yea the middleware actually depends on them not being emitted in a sense. (Would just be noise)
