### ISSUE TITLE
Review submission flow for Edge wallet.

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#518]
When user is using Edge wallet, we need to close the submission form on tx `sent` method.  Example is when buying Participation tokens.

User clicks submit but form stays, user has to manually click X to close the form. Didn't test more than PT, b/c Edge is only available on mainnet.
...

@tomhaile @serena - Need to discuss user flow for edge wallet, when sending tx
 -Chwy5
...

 I’d like to show a pending state where we are waiting for the edge signature, and then a success message. @tomhaile is that fitting for this need?  Is it needed for all forms? 
 -sharkcrayon
...

I'd have to figure out why the user sites on the reporting/dispute form and doesn't get redirected back to reporting-market or reporting-dispute markets page. 

Let's do some investigation. I'll look at it and get back.
 -bthaile
...

👍
 -sharkcrayon
...

@tomhaile  any findings here? 
 -sharkcrayon
...

Approval: Edge wallet users see modal for approving, looks good

Trading: they click confirm then trade happens, they don't see costs of trade. 

Reporting: user is shown gas cost and has to confirm. looks good

Finalizing: user clicks on finalize button and nothing appears to happen, they actually signed the tx. but button doesn't disappear until market reporting state updates. So use could click on the finalization button many times, therefore wasting gas.

Claiming Proceeds: same as finalization button, user clicks to claim and nothing happens, state has to update so that the button disappears. they could click on it multiple times and waste gas.

Reporting claim: has modal so at least user knows gas costs and what they are going to get, looks good.

I think having a confirmation modal for these actions would show the user gas costs and they can make more informed decisions. Actually probably want a confirmation modal for trezor and ledger as well.

@serena 
 -bthaile

**Comment by joeykrug** [comment]
Trading: they click confirm then trade happens, they don't see costs of trade.

Reporting: user is shown gas cost and has to confirm. looks good

Finalizing: user clicks on finalize button and nothing appears to happen, they actually signed the tx. but button doesn't disappear until market reporting state updates. So use could click on the finalization button many times, therefore wasting gas.

Claiming Proceeds: same as finalization button, user clicks to claim and nothing happens, state has to update so that the button disappears. they could click on it multiple times and waste gas.

These 4 need fixed

**Comment by Chwy5** [comment]
Design needs to understand for future user flows of various wallets we use....@cillian
