### ISSUE TITLE
Trade multiple times glitch

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#533]
https://www.reddit.com/r/Augur/comments/4boex1/trade_glitch/

**Comment by Andrew547** [comment]
I wrote the original reddit post - just signed up so I could post issues here instead.

I just found/figured that my account was likely deleted, possibly days ago. I didn't know it until now because I was able to log in and make trades - though it was generally glitchy but I chalked it up to the beta. I couldn't log in after clearing the browser cache so I created a new account with identical information and it looks like I am starting over again from scratch. I've made a few test trades and so far everything is smooth.

**Comment by Andrew547** [comment]
Though I was optimistic having an expired account was the cause and a new account the fix, it looks like it happened again. Not sure because the trade froze, but going in for 1000 shares appeared to put me on track for 2000.

Trade commitment hash:
-0x716c8c569887d245cab507a5072a3263c6267ce6c6f885c995265e88fbd306e8
Trade commitment sent. Waiting for confirmation...
Trade commitment sent. Waiting for confirmation...
Trade commitment confirmed. Sending trade...

**Comment by tinybike** [comment]
Combined with #615
