### ISSUE TITLE
Add users REP staked per market on each round and outcome.

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#573]
Need additions to portfolio reporting page where the user will be able to see their REP staked on which outcome in each dispute round. 

This will give the user the ability to track their own reporting history per market.
...

I think this was the second piece to the Portfolio -> Reporting changes. Would need design for this addition.
 -bthaile

**Comment by matt-bullock** [comment]
We can show the users a stake on an outcome within the current window - on the cards. But to show the historical staking data we'll probably need to reveal this is a modal that can be launched from the cards and/or at the top of the dispute form. I'm leaning towards a small section at the top of the dispute form because this way it can it accessed from both the cards and the market page

**Comment by pgebheim** [comment]
@Chwy5 -- I'm not sure the status of how this is handled in v2 -- Do you think this can be closed / am I missing where it's considered?

**Comment by Chwy5** [comment]
Can close or push to post v2 (not super important imo)
It wont be on the portfolio pg
we are handling this a little differently, We will show the total staked in the reporting section, but if we want to add the ability to show each rounds stake, we can make a modal for that....but can be pushed post v2.
