### ISSUE TITLE
Add queue to UI for unsigned transactions

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#592]
Alex mentioned on Discord that we should consider refactoring augur.js to keep both a virtual state for users' balances and an actual queue of actions. In addition to this, he suggested having a UI component to see all relevant pending/in-flight actions the user is taking. We already have the Notifications section, which is similar, but this would contain more information and be something for submitting queued-up unsigned txs.

"its sort of a large app-wide thought I think. It might be specific to the UI it happens in depending on context. A generic solution may also be the right call to formalize what the user should expect
they do, but thats a bit different than having a pending queue for unsigned txs."

"there might be an opportunity for some more significant UX change here where theres a persistent UI component to see all the relevant pending and in flight stuff you want to do."
...

This will need further discussion. Just wanted to create this for now so we can track it.
 -adrake33

**Comment by sharkcrayon** [comment]
I'm not totally clear on this @adrake33 @nuevoalex 

> We already have the Notifications section, which is similar, but this would contain more information and be something for submitting queued-up unsigned txs.

In what situation do users have queued-up unsigned txs that they have just triggered (like while creating a market with liquidity)? To step back, what problem is this trying to solve?

**Comment by nuevoalex** [comment]
Creating a market with liquidity is one. Trading is also a case.

This is trying to solve and provide more structure to the notion that we sometimes will need to queue txs and fire them off after another tx has been mined rather than after it has been sent.

Right now we just have the user sign the first of possibly many txs then let them go on their way and at _some point in the future_ pop up another tx. This is bad for multiple reasons:

- They dont know what the tx popup is for potentially
- For trading and market liquidity while the tx is in flight the UI behaves like they have no assets currently in pending state. For example If I sign a tx to pay 10ETH to buy shares the UI acts like I can still spend that 10ETH.
- We lose context of any pending txs on refresh I believe for trading.

Really operations like trading are more of a commitment to sign multiple txs until some state is reached, but we dont convey this in the UX/UI right now and dont organize the code governing this in Augur.js well either.

**Comment by adrake33** [comment]
Yeah, this conversation on Discord originally started when chwy reported that he had created a cat 5 market with pre liquidity. He signed 8 signing boxes (and had about 15 more orders to sign), and the sign boxes stopped popping up, so it was unclear what had happened.

**Comment by sharkcrayon** [comment]
Ah ok, I see. @matt-bullock and I will have to discuss this.

**Comment by joeykrug** [comment]
maybe in notifications show queued but unsigned ones
