### ISSUE TITLE
Show tentative winning outcome even if user not logged in

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#615]
User not logged in the top of the market trading form says "Reporting" The tentative winning outcome is known and should be displayed. Could just grey out the 'dispute' button when market is in dispute and user isn't logged in.

![screen shot 2018-12-05 at 8 13 59 am](https://user-images.githubusercontent.com/3970376/49519092-d2fd4880-f865-11e8-8613-78fd9196f939.png)

![screen shot 2018-12-05 at 8 13 49 am](https://user-images.githubusercontent.com/3970376/49519100-d690cf80-f865-11e8-832f-34ab1c31f083.png)

Requested by @MicahZoltu.

**Comment by phoebemirman** [comment]
also check that markets in awaiting_dispute_window show their tentative winning outcome

**Comment by phoebemirman** [comment]
@matt-bullock should this be disabled (with a tooltip possibly) for non-logged in users or hidden?

**Comment by matt-bullock** [comment]
@phoebemirman I recommend always showing the tentative winning outcome. The dispute button can be left how it is for now. If we change how this is displayed when not logged in then we need to look at all instances of disabled buttons when not logged in. There are enough indicators throughout the site which show that the user isn't logged in  - you can't see your account, portfolio etc. I'd like design to address this issue at a later date.

**Comment by phoebemirman** [comment]
ok!

**Comment by MicahZoltu** [comment]
@matt-bullock The problem with the missing Dispute button is that it can mean two different things:
1. The market is not eligible for dispute, because it is waiting for the next reporting window.
2. You are not logged in.

As a user, I was in scenario (2) but I thought the missing Dispute button was due to scenario (1).  It was just that I got logged out at some point (I think I had to restart my browser or something) and didn't notice that I was logged out.

Side note: I think a user being able to function within the UI without knowing whether or not they are logged in is a good indicator of success in design, so kudos on that.  I didn't lose enough functionality by being logged out that I noticed, the missing dispute button was one such feature that I lost but most everything else worked.

**Comment by matt-bullock** [comment]
@MicahZoltu those are good points. We need a solution that shows the market is ready for dispute but also indicates to the user why it's disabled. Or if the button is in its normal state and the user clicks it whilst not logged in there should be some kind of prompt telling them to log in. @sharkcrayon any thoughts here?

**Comment by sharkcrayon** [comment]
That's a fair point. I'm not sure what a good solution to this is. @MicahZoltu Would it be clearer if we broke down the Phase information into "Designated Reporting", "Open Reporting", "Upcoming Dispute", "Available for Dispute", or something like that?

That's just an initial idea. I'm not sure it's a good one.

**Comment by MicahZoltu** [comment]
I'm not sure on the terminology (as a novice user, those statements don't mean a lot to me) but I do like the gist and those are probably "good enough" terms to get started with (an improvement over current system).
