### ISSUE TITLE
AS: notification UX issues  

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6289]
1. if i have a notification that requires a transaction, after i action the transaction: 
- the notification moves down to the bottom of the list (it shouldn't) 
- there is no indication of a transaction processing so the user is left in limbo 
- it disappears after X amount of time (user is left questioning what's happening) 

Two recommendations to fix the UX here: 
1. Add a processing state to the notification button so users know something is happening
2. Don't move the notification to the bottom of the list. Users may have a lot of notifications and won't see it at the bottom if something fails etc 

The loading state would be a simple spinner added to the button: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/80c11594-f0da-4922-bafd-83f3a0ec2d1d)

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=14842%3A3997

@JohnDanz  use pendingQueue to keep track of transactions that are in transit. PendingQueue is used to track initial reporting and market creation now.

**Comment by JohnDanz** [comment]
So the problem with this is the way our notifications work we don't have access to anything that would allow this to work consistently. We need to structure our data so we have block times for notifications. 

For example, let's say we have 25.00 unclaimed REP from buying participation tokens.

What we do to figure out if we display a notification or not is akin to "does this user have unclaimed rep, and how much" that information is in our state. However we don't have anyway of saying "when did the 25 unclaimed rep we have first become available to be claimed?" which is what we need in order to achieve an ordering based on when notifications last updated so that they stay in one spot.

the way we sort notifications currently is very simple. new unread notifications go to the top then everything else is in a 2nd group of read notifications. The reason it moves is the second it becomes read and no longer new it jumps down into the 2nd group of notifications. Because they don't have information on time, it's impossible to keep their location given our current setup. We would need to have the SDK return a block time or find some other way of calculating this then simply sort notifications by block time. This isn't something we can easily do before v2 launch and should look into it post v2 imo.

**Comment by cillianhunter0** [comment]
@JohnDanz to confirm, you're saying point (2) on this ticket is a non trivial change and recommend pushing? 

Point (1) is still being worked?

**Comment by bthaile** [comment]
@cillianhunter0  New notifications are on top. if the user views a notification it is no longer New and will show up after New notifications. I think this can be closed. @Chwy5  your call

**Comment by Chwy5** [comment]
closing
