### ISSUE TITLE
Add messaging to notify user when they have complete sets

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#636]
@Chwy5 suggested in today's standup meeting that we should add some way to tell the user they have complete sets. @sharkcrayon suggested showing this in the Portfolio:Positions page.

**Comment by adrake33** [comment]
This may need more input from chwy/Serena. The idea suggested was that we would add a message to the card on the Portfolio:Positions page for markets that have complete sets.

**Comment by sharkcrayon** [comment]
![image](https://user-images.githubusercontent.com/4355755/49671689-ec4cf300-fa25-11e8-99a1-9e21a65c6ca8.png)

**Comment by Chwy5** [comment]
That notification is only sufficient to a casual user with few positions.  Any real trader/bettor/serious user, liquidity provider....that notification is limited at best.   The most important feature to a user whether centralized/decentralized is still the ability to know where all your money is and be TTP.  Complete sets will mean nothing to the majority of users (bettors/traders) have no idea what that is.

I had 40 markets open and I had to scroll through and open up My Positions in each one to see if I can get me eth back, including going through additional resolved markets.  Users should not have to search to find their eth....any type of notification upon sign in or at the top of the portfolio pg is needed

**Comment by sharkcrayon** [comment]
@Chwy5 What would the notification at the top of the portfolio page say?

**Comment by Chwy5** [comment]
You have complete sets or You have complete sets to sell....

if a user clicks on it it should take them to the market with the complete sets or a link to where they can sell them if they wish (though i think the first option is better in the event of having many markets with complete sets)

But we want to grow trading and getting shares reverted back to usable eth (especially with our delay in settlements) is very important - at least in betting sites/exchanges get money back it is usually dispersed into other markets

**Comment by sharkcrayon** [comment]
@Chwy5 But a user may have complete sets in multiple markets, especially if they are a liquidity provider. Are you saying we need a place that lists out all markets in which the user has complete sets? It sounds to me like the market cards on the portfolio page just need to more scannable/compact.

The fix that John is putting in place (screenshot-ed above) would at least make it so you can see which markets have complete sets from the Portfolio page, so at least you wouldn't have to click through to a market to find out. You'd still have to page through, since we only show 10 market cards at once, so that is certainly a shortcoming.

If the portfolio page market cards were more compact and we showed more at once, looking through your markets there for complete sets would become a much easier task.

**Comment by Chwy5** [comment]
Traders do not want to have to go search.....
Trader don't like to leave a trading pg, let alone spending time searching to get their eth back

**Comment by sharkcrayon** [comment]
Talked about this on standup. We can go ahead with John's solution for now (from the screenshot above) and then when we redo the Portfolio page it will be important to have a version of the market cards that's very condensed and filtering options to allow users to see just the markets that have complete sets, or just those with money available to claim, etc.

**Comment by adrake33** [comment]
Sounds good. 👍
