### ISSUE TITLE
Order failing if existing order is already Taken

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6380]
If 2 users rece to take an order off the book and 1 person gets it, the 2nd user is getting a failed trade.....Their trade should not fail, it should be added to the order book....Only if a user changes the "advanced" setting to fill only should the order not go to the book...

![2-21failed.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/5d8a39df-ffa3-4048-95df-2e1afe927e4b)

**Comment by bthaile** [comment]
If the order that was signed fails to trade. Then user would have to sign a new order to be put on the order book. 

best case scenario UI handles the failure in a way that conveys to the user the tx failed.

**Comment by bthaile** [comment]
Need some feedback from @pgebheim  on options

**Comment by pgebheim** [comment]
@nuevoalex -- this was fixed in your contract PR last weekend yes?

**Comment by matt-bullock** [comment]
Got this error when me and chwy tried to fill the same order. His went through, I got this error

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/00551027-3444-482f-84ca-eb1ace6ebd87)

Rather than going onto the book, it failed

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/edb3a4f5-7d25-44a2-bddb-37512b820253)

---

Another instance we tried to take parts of an order. Chwy's order went through, Tom got a real error message, I got this fake message and then my trade went through

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/62621a73-4ffc-4f3f-a7e4-842056eddffa)

**Comment by Chwy5** [comment]
Getting different errors than last time, but still having failing transaction (not all the time either)

Sometimes it results in results in the fake error, where tx resubmits on its own

But when Matt, Tom and I tried trading all at once, Mine went through, matt got fake error that resubmitted and filled and tom's failed (with no resubmit

**Comment by pgebheim** [comment]
Let's try this again now that the fake error is fixed -- can do tomorrow morn with y'all?

**Comment by pgebheim** [comment]
We tested this and it's now working properly, except we found another bug noted in another ticket.
