### ISSUE TITLE
Add key import/export to the new UI

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#655]
This should work exactly as it did in the old UI.  Should be able to more-or-less copy-and-paste the code over.

**Comment by thinkloop** [comment]
Comment from other issue form joey:

> "Please download your encrypted account information now! If you lose this file, we have no way of restoring your account."

> It should autodownload too. There are a bunch of ways of doing this, best way to do it that works on almost all browsers is what we used for crowdsale app. Was a bit confusing to me until i realized had to click to download.

> Should also add something like ether.li as a wallet system

**Comment by JohnDanz** [comment]
I haven't done the auto download part, if you mean that should take place on initial registration/login in, but we do have the download button on the account page for this purpose. Also merged in the ability to import an account so that is now in place as well. Closing this issue. If we want to do an auto download on registration, lets open a new issue for that.
