### ISSUE TITLE
Goals for Performance Optimization

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#6701]
Optimize speed in various ways

Original list to keep track so it doesn't get split into a bunch of slices and then we don't know if it's actually done in a week when I ask:

 - [x] 100s of markets on the site
 - [x] optimize to lower eth calls and get numbers for how many are happening for merely having the page open and how many calls are happening when 100 orders per second are being created and when 1 trade every 10 seconds is happening
 - [x] market page should load in a few seconds
 - [ ] market list should load in a few seconds
 - [ ] 1000 orders per second (in one market and 100/s across 10 markets)
 - [ ] test with user accounts that've traded in 100s of markets
 - [ ] and with accounts that've done 1000s of trades and have 100+ open positions

**Comment by pgebheim** [comment]
@joeykrug Splitting this into an epic because it kinda goes wide

**Comment by pgebheim** [comment]
@joeykrug when #6813 closes we'll have the ability to create the test scenarios you described.

We do need a plan for actually being able to measure some things like throughput, latency -- whether that's just anecdotally by using the UI or something more formal.

**Comment by pgebheim** [comment]
Current list:
Eth call optimization -- we're going to not spend more effort on this until we have some evidence that its going to be impact for performance. Currently we're doing ~10 eth API calls per block, plus 1 eth call per 200 orders during initial sync, and eth calls in blocks when orders are being streamed in.

100s of markets -- having 100s of markets works great with no performance issues, until we're expanding orders to match those.

1000s of orders (per second?) -- currently we're waiting on optimizations from 0x to determine how well this will scale up. At 1000 orders behavior in the UI still worked, now at 5000-7000 orders it is too slow and laggy to show order books quickly.

Loading Times:
   - Hotloaded market loads in a few seconds WITHOUT ORDERS
   - Market List page is slow to rank markets because it needs orders to do so.
