### ISSUE TITLE
Finalize button missing

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#692]
A user can only see to finalize their markets in Portfolio, under My Markets, under resolved

Currently in the Portfolio pg under **Positions**, under resolved, users can NOT see if their markets need to be finalized, unless "clicking" on their market to select it and bring it to the trading pg....once on the trading pg a user can see the finalized button

@phoebemirman believes losing positions are currently not being displayed to users

**Comment by phoebemirman** [comment]
finalize button is only being shown on positions page if you have a winning position

**Comment by adrake33** [comment]
I think the Finalize button should always viewable on the My Markets page because clicking it will distribute the validity bond (in addition to setting the winning payout distribution hash for the market & redistributing REP staked on non-winning outcomes to REP holders who staked on the winning outcome).

Even if the user has a losing position, they could potentially stake REP on an outcome that ends up being the winning outcome. Should we also be checking to see if they staked on a winning crowdsourcer?

**Comment by adrake33** [comment]
I think it makes sense to not show the Finalize button if the user has a losing position (provided that they did not also stake REP in the winning outcome). However, if they have a losing position but still staked on the winning outcome, wouldn't it make sense to show the Finalize button in that case?

**Comment by adrake33** [comment]
What are your thoughts on when the Finalize button should be shown, @sharkcrayon? It makes sense to be consistent in when it's displayed on the trading page vs Portfolio:Positions page. However, I'm not sure we need to show it when the user has a losing position (and doesn't have staked REP in the winning outcome). It seems like the button ought to be hidden when clicking it won't benefit the user in any way.

**Comment by Chwy5** [comment]
It is a very weird user experience to see it in one location and accidentally come across it in another and not understand why i see it in one spot and not another.....
Not really sure we can convey to the user why they may see it in one spot and not another....probably easier to have it consistent whether winning or losing

**Comment by adrake33** [comment]
~~Hmm, I can see how it would seem weird to users if it’s not always visible, but on the other hand, it’s a waste of gas for users who don’t need to click it. Maybe we could show some sort of message to the user instead of the Finalize button when they don’t need to click it?~~

@chwy5 Sorry, realized I read your post too quickly. I agree it should be the same behavior in both locations. I just meant we should hide it on the trading page whenever we hide it on the Positions page

**Comment by sharkcrayon** [comment]
I'm torn between only showing it to users if it would benefit them and showing it to all users regardless.  It's possible there are some altruistic users out there who would want to finalize the market even though it wouldn't benefit them financially. Also, what Chwy is saying still applies if we only show the button selectively, because a market creator would see the button on the My Markets page and possibly not see it on the Positions or Trading page.

Maybe for the sake of simplicity we should just always show the button.

**Comment by Chwy5** [comment]
Is there anyway to tie the finalize button, to include cancelling all open orders after the market is resolved....Then it will still have a function for users who may have lost bust still need to spend eth to cancel their open orders and close out of the market

**Comment by adrake33** [comment]
@Chwy5 Yeah, we could certainly add that functionality when the user clicks the Finalize button. I like the idea of doing that.

@sharkcrayon If we want to make the Finalize button always visible as well as cancel all of the user's open orders, it'd be good if we could make it clearer to the user what the Finalize button will do. Could we put a tooltip next to it that explains this?

**Comment by sharkcrayon-augur** [comment]
@Chwy5 @adrake33 I don't think the Finalize button should also cancel all of the user's open orders. They may almost always want to cancel open orders at the same time as finalizing, but I don't think there's a straightforward or graceful way to make it clear those two actions are tied to a single button. It's better to keep them separate and not complicate the UI.

Let's move forward with showing the Finalize button to all (logged-in) users, even if clicking it may not benefit some. We'll leave the decision to click or not up to the user.

**Comment by adrake33** [comment]
Ok, sounds good to me.
