### ISSUE TITLE
Invalid market not filtering out from invalid filter

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7360]
Need to confirm if Invalid Filter is working properly....see screenshot, should this market have been filtered out?

![4-17invalid.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/6f9b49fe-85c7-42f4-b8d4-a4b36c6274f6)

Also, this market isn't marked Invalid, not sure why not

![image](https://user-images.githubusercontent.com/3970376/81418696-ae6c6680-9112-11ea-87e8-282dcc0e6923.png)

**Comment by joeykrug** [comment]
depends on gas price. If you want to see if the filter is working, put an order in for like 25 or 50 cents

**Comment by Chwy5** [comment]
This failed doing 100 shares at 25 but worked doing 300 shares at 25

Also worked doing 100 shares at 50

**Comment by nuevoalex** [comment]
@Chwy5 Do you know what the gas price was at the time? Another factor is how long until the market ends.

**Comment by Chwy5** [comment]
i do not

**Comment by nuevoalex** [comment]
Assuming a relatively normal gas price that would make the trade $2 and the claim $1 and assuming the first market is 1 week from expiration and the second market is 3-4 months from expiration both of these would not trigger Invalid filtering.

The minimum profit for a taker needs to be > $10 and after fees + TVOM both of these end up generating a profit of $4-5.

This does demonstrate a potential issue however which is that someone can make a "best" bid that has a small share amount to make the filter not trigger by preventing the algorithm from looking at other orders. To remedy this we can just iterate the orderbook. Most of the calculation can be precomputed once so this won't be _too_ much additional processing though it does make the filter O(n) instead of O(1) now.

**Comment by Chwy5** [comment]
This needs further review....Invalid trade 30xs @ 90 and 10 @ 99

I have a bid on invalid....this market is not being filtered out and I really think it should be....

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/fdae40b0-d165-4fe4-abe8-9471d977af47)

![image](https://user-images.githubusercontent.com/41301809/84394617-2d9a0200-abcb-11ea-9d68-38d910790410.png)

**Comment by joeykrug** [comment]
So that order will profit someone $10 if they bet against invalid and the market isn't invalid.

What's the gas transaction cost in dai to place a trade and claim winnings? I'll bet it's higher than $10, which means the code is still working properly

Also @nuevoalex is this true "This does demonstrate a potential issue however which is that someone can make a "best" bid that has a small share amount to make the filter not trigger by preventing the algorithm from looking at other orders"

The code says this // A Market is marked as True in the invalidFilter if the any bid for Invalid on the book would be profitable to take were the market Valid
which seems to imply the above isn't right? If the above is right we should fix

**Comment by nuevoalex** [comment]
@joeykrug Yea I fixed it when I noticed that problem: https://github.com/AugurProject/augur/pull/7733

If the profit for this trade is only $10 it definitely won't show up as it must be > $10 _after_ considering fees and TVOM

**Comment by joeykrug** [comment]
Oh cool

And yeah that's exactly my point

**Comment by Chwy5** [comment]
closing
