### ISSUE TITLE
Universe and Market addresses appear empty in Event logs

### ISSUE THREAD

**Issue by afterether** [AugurProject/augur#7388]
I am dumping event logs in local testnet setup and I am finding empty `Universe` and `Market` addresses (set to zeros). Currently I have dumped `MarketOIChanged` and `OrderEvent` event logs, but I am suspecting this is going to repeat in other events too.

So, the question is, is this supposed to work like this or is it a bug? Having this data set correctly would facilitate event processing, btw.

Screenshots attached.

![uninitialized_fields_in_event_logs](https://user-images.githubusercontent.com/33187946/79785032-d2553d00-8308-11ea-838b-3a67ab004054.png)
![dump_function_shot](https://user-images.githubusercontent.com/33187946/79785042-d6815a80-8308-11ea-9312-75c389fd70da.png)

**Comment by pgebheim** [comment]
Hey @afterether -- first question which abi are you using and what are you doing to dump these? Is it possible that this is an issue with how your code (or the library you're using) parsing addresses, as both Universe and Market are an address?

**Comment by afterether** [comment]
Compiled the ABIs with `solc` vers 0.5.15 compiler yesterday on the yesterday's master branch. I am dumping them with this code: https://github.com/afterether/augur-extractor

**Comment by pgebheim** [comment]
The abi is pre-built and available here (fwiw).
https://github.com/AugurProject/augur/blob/master/packages/augur-artifacts/src/abi.json

As you can see we specify those fields with the address type:
https://github.com/AugurProject/augur/blob/master/packages/augur-artifacts/src/abi.json#L8051

My question is -- is your ABI decoder handling those appropriately or is it failing and defaulting to 0x0?

**Comment by pgebheim** [comment]
@afterether -- Also I'll note that we do all of this work (and more) to make a local database of all the augur data. You can use the augur standalone server to create it, inserting that data into a local LevelDB.

From within the monorepo this can be run as follows:
```yarn flash sdk-server```

Although it's nice to have multiple options, I'd recommend attempting to use the SDK as well since it provides a ton of functionality (and is the same code that powers augur ui).

**Comment by pgebheim** [comment]
@afterether -- OH! @nuevoalex pointed out that these two fields (Universe, Market) are indexed fields (topics). Topics are stored separately from data so that they can be efficiently scanned and filtered.

Random tutorial on the subject:
https://codeburst.io/deep-dive-into-ethereum-logs-a8d2047c7371

**Comment by afterether** [comment]
@pgebheim thanks!

**Comment by pgebheim** [comment]
@afterether no problem. Looking at your code, you already parse and iterate through the topics, so it looks like you just need to merge everything into your struct there!
