### ISSUE TITLE
Mesh Issue recovering from sleep mode

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7473]
If I leave my account open and my computer goes into sleep mode, When I reawaken my computer and go back into a market, I can only go from Red status (dot) to Yellow(dot - degraded service)....sometime s the order book filters back in and other times it doesnt and I still need to refresh my browser to fix it and get back to green.

Can we refresh this automatically when a user comes back from sleep mode

![4-26a.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/cefc2c5c-4e4c-4f36-9acf-d1eff416d13b)

[Uploading... 4-26b.jpg ]

**Comment by pgebheim** [comment]
My first thought here is that I think those errors would be expected. When your machine comes back from sleep it doesn't have network access immediately and it will take time for Wifi to reconnect, and for things to come back to normal.

Then the issue comes down to what we can detect. I do thin that an automatic refresh is possible if we catch any of these errors. Currently we have a top level error handler on the Mesh that will attempt to restart it, but we can see if these websocket errors get handled there and perhaps do something different with them.

@nuevoalex -- this will probably be a good thing to spend some time with, my guess is we can make it better but not perfect.

**Comment by pgebheim** [comment]
btw, gonna leave the type/bug label for now but I don't really think this is a bug per se.

**Comment by Chwy5** [comment]
I am still seeing these errors and my market is stuck in the red. telling me to refresh this pg.  Is this the expected behavior or did we add in the automatic refresh....

![4-28rec.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/6f547b42-3afd-4ac2-acd6-d403c7a5e162)

**Comment by pgebheim** [comment]
This is the best we can do right now since we don't get those LevelDB errors in our app code.
