### ISSUE TITLE
Portis Not working for signup on mobile

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7478]
On Mobile - try signing up for a new account on Portis after submitting it takes user right back to the portis signup screen (no act gets created)

**Comment by andrewdamelio** [comment]
@chwy tested on iPhone + safari and it worked fine.

What device/browser are you having issues with?

**Comment by Chwy5** [comment]
Joey and tom on iphone safari and I am on chrome on Galaxy s10

**Comment by pgebheim** [comment]
@andrewdamelio -- Do you have cookie / popup blocking already excluded for the v2.augur.net domain by chance? Worth checking --- @bthaile is on iOS 13.4.1 in safari and is getting a login loop when attempting to login with Portis.

**Comment by andrewdamelio** [comment]
I do not!
let me try updating to 13.4.1

**Comment by andrewdamelio** [comment]
@Chwy5 @pgebheim I updated to 13.4.1 and don't see the issue.

@bthaile do you remember, are you clicking Allow or Disallow for email display on Portis signup?

**Comment by andrewdamelio** [comment]
@Chwy5 @pgebheim @bthaile 

Ok i **think** figured out whats going on here. 
It seems like the second Portis modal (Allow/Disallow) gets blocked by the market list loading - it waits until `Syncing Complete - SDK Ready`

So if you create a Portis account and syncing is still happening after you finish you will get stuck here until Sync is finished.

<img src="https://user-images.githubusercontent.com/1683736/81307808-0f326b00-904f-11ea-9719-d141725af867.PNG" width="333" />

Once Sync is complete, you should see the next steps

<img src="https://user-images.githubusercontent.com/1683736/81307896-2a04df80-904f-11ea-9b16-a07b09bc2d7e.PNG" width="333" />

<img src="https://user-images.githubusercontent.com/1683736/81307908-2cffd000-904f-11ea-8121-ef84357193f9.PNG" width="333" />

Since on mobile safari syncing sometimes takes forever this issue appears more so there than on desktop.


In terms of a fix, i'm not sure what the right UX is, especially with the limitation of he Portis iframe not being under our control. 

Easy fix could be to disable (only) the signup button, until Augur is fully loaded to avoid getting the permissions window blocked.

**Comment by pgebheim** [comment]
Is there a reason we need to wait for syncing to complete to continue?

**Comment by andrewdamelio** [comment]
@pgebheim FYI i took a look at this yesterday, looks like we don't have the issue with Fortmatic/Torus so it isn't related to what i was thinking above.. 

Going to look into the Portis flow today to see if what could be block / waiting on SDK there.

**Comment by pgebheim** [comment]
@andrewdamelio Status on this?

**Comment by andrewdamelio** [comment]
ready to be tested again -- working for me now after some of the onboarding fixes

**Comment by matt-bullock** [comment]
Working for me. Closing
