### ISSUE TITLE
Showing wrong info in acct dropdown

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7509]
We are currently showing the users wallet who they used to sign up....we should be using the users email address or phone number they used to sign up.

The only exception to this is if using MM/Web3 (then we show MM/Web3)

**Comment by andrewdamelio** [comment]
some clarifications @Chwy5 

- We are unable to show phone number in the account info topBar, we don't get this info back from Fortmatic, so most cases Fortmatic will actually show wallet address
- For Torus and Portis we can only show email if the user allows it... otherwise we show the Wallet Address (never phone number for these)
- I will update the TopBar to show EMAIL (when it can) otherwise it will show the wallet address
