### ISSUE TITLE
Market Search not working properly

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7593]
When I enter NFL or Draft, the market I was looking for does not appear

**Comment by bthaile** [comment]
Question:

The market you were looking for is there more than one with the same title?

**Comment by bthaile** [comment]
notes:
loaded up all the markets in UI state, so that I could compare UI state with SDK searches

```
Object.keys(state.marketInfos).filter(id => (state.marketInfos[id]).description.includes("Draft")).map(id => ({id: state.marketInfos[id].id, title: state.marketInfos[id].description, state: state.marketInfos[id].reportingState}))
```

this command give me 15 markets

await AugurSDK.getMarkets({
  search: "Draft*",
  templateFilter: "all",
  limit: 22,
  includeInvalidMarkets: true,
  universe: state.universe.id,
});

Getter misses returning 2 markets that have the same title.

"0x332B133eB8Baf69CF211E45C50A19b451B4b2dEA":  2020 NFL Draft: Who will be the first Wide Receiver selected?
"0xBc3930639c93092a66F6e63A32c6D4F0406Da555": 2020 NFL Draft: Who will be the first Wide Receiver selected?

**Comment by pgebheim** [comment]
@justinbarry -- We tried this using all the preset modes to no avail...

**Comment by Chwy5** [comment]
working - closing
