### ISSUE TITLE
Forward slash separators getting removed from market cards tags

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7936]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/3312810a-2d2b-4c67-b953-273414c1e1a9)

**Comment by bconfortin** [comment]
@matt-bullock 
We currently do that in CSS using `text-overflow: ellipsis` and it's all automatic.
Firefox is the only browser that supports a custom string like `text-overflow: "... /"`, since Firefox 9, which launched in 2011. Since then, no other browser added support to the custom string property, sadly.
Source: <https://caniuse.com/#feat=mdn-css_properties_text-overflow_string>

Talked to the guys on standup and the effort to make that work using JavaScript instead of CSS is not worth it, at least not right now.
