### ISSUE TITLE
Provide Guidelines for what Invalid means on forking migration & trading pages

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#795]
Separating this out from https://github.com/AugurProject/augur/issues/594, since these are not as essential (or quick) to implement as adding this info to the reporting/dispute pages.

**Comment by MicahZoltu** [comment]
Preface: Getting _any_ guidelines into the UI is better than delaying on exact copy, so please don't let the following slow down development of this task.

I would like to discuss the copy used in these tooltips.  While the tooltip suggested by @sharkcrayon in #594 is certainly friendly, I worry that it loses some nuance from the original guideline suggestions I had.

Copy used in #594:
> Please choose an outcome below based on the resolution source at the time the market ended. The market should be considered invalid if it is opinion-based, unclear, has more than one valid outcome, or the outcome wasn't known when the market ended.

Original guidelines I drafted:
```
* INVALID: The market is clearly trying to subvert the reporting system or scam traders/reporters.
* INVALID: At market creation time, it was known that one or more of the outcomes will never payout.
* INVALID: The question is subjective in nature.
* INVALID: The outcome was not known at market end time.
* INVALID: The title, details and outcomes are in direct conflict with each other.
* INVALID: There are strong arguments for the market resolving as multiple outcomes.
```

Some of those I think there isn't enough agreement on to put in the reference UI at this juncture and the wording on others could be improved and a couple more have come up recently, so lets adjust the set to:
```
* INVALID: The question is subjective in nature.
* INVALID: The outcome was not known at market end time.
* INVALID: The title, details, end time, resolution source, and outcomes are in direct conflict with each other.
* INVALID: There are strong arguments for the market resolving as multiple outcomes.
* INVALID: The resolution source does not provide a readily available answer.
* INVALID: The resolution source provides different answers to different viewers.
```

I don't feel that the current copy captures the above guidelines (partly because some are new), but I also am concerned that formatting them into an easy-on-the-eyes paragraph results in them losing some of their precision.  These guidelines are meant to be "technical" statements (like legalese), not vague friendly statements.  While I am not die-hard set on the bullet format (though I do prefer it personally) I think that separating them out is important to avoid any misinterpretation.

**Comment by adrake33** [comment]
Thanks for updating this list, @MicahZoltu. The bulleted list takes up a lot of space, but is easy to read. I'll try changing it to this and see how it looks.

**Comment by MicahZoltu** [comment]
If we think it would help, we may be able to tighten up some of those lines or split them into multiple lines.  We can probably get rid of the prefix on each in favor of an opening line like:

> The market is INVALID if any of the following are true:
> * The question is subjective in nature.
> * The outcome was not known at market end time.
> * ...

**Comment by adrake33** [comment]
Yeah, agreed. I was planning to remove the "INVALID" from each item in the list.

**Comment by adrake33** [comment]
@MicahZoltu I've updated the copy for the reporting/dispute pages in https://github.com/AugurProject/augur-ui/pull/2597. Will leave this ticket open since it also still needs to be added to the forking migration & trading pages.

**Comment by adrake33** [comment]
@MicahZoltu @Chwy5 For the trading page, where would you suggest putting these guidelines? I talked to @matt-bullock about this, and he suggested doing it as a tooltip at the end of the market title using the (i) icon. Another alternative he suggested would be putting it at the top of the market list page, but IMO it would make the most sense at the end of the market title on the trading page.

One other thing Matt mentioned was that we should probably add a note to the end of the tooltip text that says that markets can be reported on and resolved as invalid, in case some users are unaware of this.

**Comment by Chwy5** [comment]
I think we need an FAQ section (add tab to top menu bar) and I would add a
detailed spot in there

I feel like guidelines are better suited in the market creation section.

**Comment by MicahZoltu** [comment]
What about a section after the Additional Details box on the market page?  It could be collapsed by default (like the additional details are) and the visible portion could read something like, "This market will be invalid if [click for more]..."

To me, this information should be located near the title/additional details since these guidelines _are_ part of the definition for the market.  I don't think they need to be immediately visible, but I do think there needs to be strong breadcrumbs (more than just a tooltip or info button).

**Comment by Chwy5** [comment]
Agree with Micah, i think we need something stronger than a tooltip for this.

**Comment by adrake33** [comment]
Those are good points. A tooltip isn't very noticeable, but a collapsable section would be. Eventually, it would be good to have an FAQ section as chwy suggested, but this particular information would be good to have in the trading page itself, since users might not think to check the FAQ section for it. For now, let's implement this as a collapsable section after the Additional Details.

**Comment by Chwy5** [comment]
Yeah sorry want clear on that....Faq would be in addition to other location

**Comment by pgebheim** [comment]
@Chwy5 @cillianhunter0 @matt-bullock -- Was this done during design?

**Comment by Chwy5** [comment]
No....I dont think it really belongs on the trading pg....for V2 maybe an (i) with a tooltip as what invalid as an outcome means, but not added for V1

**Comment by cillianhunter0** [comment]
Have added to design backlog

**Comment by MicahZoltu** [comment]
For context, based on anecdotal sentiment analysis from Augur Discord, this is the number one way users are getting scrammed/screwed right now.

I'm hesitant to support putting it off to v2 unless there is a strong expectation  that v2 is just about ready (which I don't believe is the case, but I am out of the loop).

I know it seems like a thing that users don't want, but at the moment a lot of people are losing money because of invalid markets.

**Comment by Chwy5** [comment]
There needs to be a different solution than posting it on the trading pg....like a warning message when signing on or clicking a market from the market trading cards....."saying something along the lines of..."Please verify all information is accurate, before proceeding"
But if I ever came to a site that said, "Warning you may be getting scammed proceed at your own risk", especially on the direct trading pg I was interested in trading on...very few would proceed.....the site would be a failure, b/c it cant be trusted and will never grow to the masses.

Redoing the Market creation process which is pre-V2 should/needs to help this as well

**Comment by MicahZoltu** [comment]
@Chwy5 Would you rather go to a site that had no warnings, and then get scammed because you didn't know any better?

Fundamentally, this is a hard problem in censorship resistant systems that doesn't have an ideal answer.  The two options are:
1. Don't educate/warn your users, a non-trivial number of them will be scammed.
2. Educate/warn your users, a non-trivial number of them won't use your product.

Personally, I am strongly in favor of (2) _until_ we can solve (1) in some other way (we somehow manage to solve the curation problem).  Other projects in the crypto-currency space have made similar value judgements, like MEW/MyCrypto with their 7 screen doom and gloom warning when you first open the site.  I think it is better to have fewer users that don't get scammed vs more users that do get scammed.

I do agree that long term we need _better_ solutions than just plastering reporting guidelines everywhere, but at the moment I'm looking for a band-aid quick-fix that doesn't divert a lot of resources off of v2 but helps address a major problem with the current UI.  At the moment we have nothing, and users are getting scammed or otherwise losing money due to lack of education about the process almost daily.

**Comment by Chwy5** [comment]
Yes this is being addressed in the new design and NO it is not being added to the new trading pg.  WE definitely agree it is needed but feel there are better places to show it.....(i.e) when a user clicks a market from the market trading cards, trying to enter the trading pg a quick pop up(might be for first time users or first time a user signs back on), saying something like (haven't thought out semantics yet)...."Augur does not create or regulate markets. Markets are created by the users. Please verify all Market details are correct before trading"

**Comment by MicahZoltu** [comment]
How far off is the vNext UI?  I haven't been following progress really, and I won't ask for a date, but it may help inform my discussions to know if the vNext UI is still in design, prototyping, implementation, or bug-hunting phase?

**Comment by Chwy5** [comment]
just dm'd u

**Comment by bthaile** [comment]
@Chwy5 can you see where this tix goes. not sure if y'all are currently investigating this during this sprint.

**Comment by Chwy5** [comment]
bandaid was added to the old version....have new placement for this in the new trading ui....closing this ticket
