### ISSUE TITLE
Losing REPs on my account but don't see any Reporting button or sth.

### ISSUE THREAD

**Issue by drkthng** [AugurProject/augur#806]
Browser: Firefox 49.0.2 (Win 7)
testpage: https://app.augur.net/

1) Go to main page
2) check REP count -> more than 50% of my reps gone
3) search Reporting button -> none there
4) search Reporting progress bar -> exists, tells me commit phase ends in 8 hours 

But no possibility to commit any reportings.

![reps](https://cloud.githubusercontent.com/assets/3247479/20144736/db2236f4-a69d-11e6-92a5-e4748533d71e.png)

**Comment by tinybike** [comment]
When was the last time you logged on? The Reporting cycle is very short (48
hours) on the test chain.

Browser: Firefox 49.0.2 (Win 7)
testpage: https://app.augur.net/

   1. Go to main page
   2. check REP count -> more than 50% of my reps gone
   3. search Reporting button -> none there
   4. search Reporting progress bar -> exists, tells me commit phase ends
   in 8 hours

But no possibility to commit any reportings.

[image: reps]
<https://cloud.githubusercontent.com/assets/3247479/20144736/db2236f4-a69d-11e6-92a5-e4748533d71e.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AugurProject/augur/issues/806>, or mute the thread

**Comment by drkthng** [comment]
logging on at least twice a day, didn't see the report button yesterday either.
Only saw it once 2 days ago when I then ran into this incident: #802

cheers!

**Comment by tinybike** [comment]
Should be resolved with the latest Reporting updates.
