### ISSUE TITLE
Trading bug - order expiration message/Missing Total Order Value

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8089]
seeing this message on the bottom and my total order value isnt filing in....market expires soon, but i should still be able to put this order in

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/eb44e918-84e9-4c31-a7d4-04476f4b3450)

**Comment by bthaile** [comment]
The error stops the total order value from getting filled in. 
main issue that needs to be looked into is why the algo is estimating a trade would take 47 minutes.

**Comment by andrewdamelio** [comment]
@bthaile @pgebheim 

The issue here is that we are using the below endpoint to calculate the buckets for standard/fast/safe TX time buckets, regardless of network.

```https://safe-relay.gnosis.io/api/v1/gas-station/```

So on kovan unless you have a super HIGH gasPrice the user will always fall into the else catch which returns in that 47mins estimation. 

```
async getGasConfirmEstimate() {
    var gasLevels = await this.getGasStation();
    var recommended = (parseInt(gasLevels["standard"]) + 1000000000);
    var fast = (parseInt(gasLevels["fast"]) + 1000000000);
    var gasPrice = await this.getGasPrice();
    var gasPriceNum = gasPrice.toNumber();

    if (gasPriceNum >= fast) {
      return 60;
    }
    if (gasPriceNum >= recommended) {
      return 180;
    }
    else {
      return 1800;
    }
  }
```

I'm unable to find a reliable kovan gasStation endpoint that doesn't rate limit without a API key. I'll add some stubbed buckets for all non mainnet networks to make this more reasonable. 

@Chwy5 to get around this in the meantime you can just set your gasPrice to something like 55+

**Comment by pgebheim** [comment]
On kovan why don't we just choose 3 levels and hard code them?

**Comment by andrewdamelio** [comment]
@pgebheim Yeah ended up doing just that 👍

**Comment by Chwy5** [comment]
fixed - closing
