### ISSUE TITLE
Trading Position Updates

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#825]
I wanna attempt to make shirt positions easier to understand by doing unrealized profit calculations for them by accounting for the netPosition of each outcome.

**Comment by nuevoalex** [comment]
What we want here is to make trading positions based off of net quantity instead of raw quantity and additionally modify the way net qty is calculated to include escrowed shares.

Currently net qty is calculated using only the number of shares actually owned. Instead it should be based off of the number of shares actually owned _plus_ the number of shares currently escrowed. We make the number of shares escrowed available in the profit loss timerseries table along with the num owned so this should be a trivial change.

Once this step is complete we should alter both the avg price and unrealized profit to be based off the net qty instead of the quantity. Currently it is based only off of the amount owned which results in an incorrect avg price when shares are escrowed.
