### ISSUE TITLE
Login-Logout sequence produces error

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#8284]
Clicking Logout, and then immediately after that Login (with Metamask) gives me this error:

![logout_login_error](https://user-images.githubusercontent.com/1125368/86403096-a512fc80-bc72-11ea-866d-178cb526586e.png)

Using the sources updated as of today's morning. Local testnet setup with a custom market.

**Comment by pgebheim** [comment]
Did this leave something in a broken state? Were you able to log in with another attempt?

Looks to me like something in the system was doing a getBalance or something and when the wallet moved into being logged out the request failed.

Can investigate if theres much impact but if not we should not spend a lot of time on this at the moment.

**Comment by nuliknol** [comment]
@pgebheim 
no, nothing bad happens. Just this error on console. I login/logout fine.
No problem, just reporting this because a system must never have any error (imho), no matter of the degree of severity.

**Comment by pgebheim** [comment]
Of the errors on your screen:
The exchange error is because liquidity hadn't been added to the rep-eth exchange. There's a deployer change to fix that.

MapStateToProps fixed.

The metamask error will spit to the console even if we handle the response correctly (ie we can't stop it from showing up) -- which is why the system still operates correctly it's ok (for now).

Another error like this all the websocket errors you'll get from the P2P mesh trying to find peers. It's not really an error condition in the system but the browser logs it that way regardless.

**Comment by bthaile** [comment]
@nuliknol on local chain. you can run `yarn flash liquidity` to get fix the issue that causes `Error: Exchange doesn't exist` 

flash is a bunch of utility scripts

Also, I'm not able to repro the logout and back in MM errors. I'm testing against kovan.

**Comment by Chwy5** [comment]
Working correctly - closing

**Comment by bthaile** [comment]
I think this is fixed with recent PRs. 
<https://github.com/AugurProject/augur/pull/8492> 
<https://github.com/AugurProject/augur/pull/8434>
