### ISSUE TITLE
Different calculation of Frozen Funds on the top panel

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#8456]
The value of Frozen Funds is calculated differently. On Order Fill action it is calculated one way, but after reloading the page, it is calculated another way. And the values don't match.

(sources as of 3 hours ago (commit fd68d4f4d11a46dcd2f2cbee9fdb12da494b8aec) , local testnet config)

Here is the screenshot before reloading (just after Order FIll action)
![ff_different_calculation_before_reload](https://user-images.githubusercontent.com/1125368/87485103-9840c200-c5fd-11ea-8c7f-2bdc4f941d32.png)

Here is after clicking "Reload" button in the browser
![ff_different_calculation_after_reload](https://user-images.githubusercontent.com/1125368/87485142-ad1d5580-c5fd-11ea-9b3b-5e081fe3e645.png)

**Comment by pgebheim** [comment]
@Chwy5 can you try to repro this?

**Comment by Chwy5** [comment]
Ill try...at first glance it just looks like a refresh issue.....His FF increase by 77 after refresh and that was the last trade he did (last trade price on Durango)

**Comment by Chwy5** [comment]
I am not seeing it....He may be blocks behind....mine is updating without need for refresh and updates fairly quick....Was he doing individual trades or sweeping the book (just bc he has the same timestamps in trade history)?

**Comment by Chwy5** [comment]
sweeping updated correctly for me as well

**Comment by nuliknol** [comment]
@Chwy5 I am running local test net config with `-f` , so the timestamp is always the same for all the blocks.

**Comment by pgebheim** [comment]
Looks to be an issue with running with fake-time in dev mode, my guess is that the UI isn't sending out the events until time moves so the UI isn't updating some data -- which is why you see it on refresh.

I recommend pushing time and see if this works right.

FWIW the fake time mode is a bit of an interesting beast, really there to test the mechanics of forking etc. I wouldn't use that for normal development.
