### ISSUE TITLE
iPad layout formatting incorrect, cutting off top and side.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#8457]
reported by `Perditus#2503` in discord
Need to check out actual iPad device if can't repro locally in mobile mode.

![image](https://user-images.githubusercontent.com/3970376/87485966-af80af00-c5ff-11ea-93ef-226287542447.png)

![image](https://user-images.githubusercontent.com/3970376/87485974-b60f2680-c5ff-11ea-9fea-9eb06a37a6a2.png)

**Comment by matt-bullock** [comment]
I'm also seeing screens getting cut off at the side on ipad. It may be because the email address top right isn't truncating when it should be, causing the entire page to shift to the right

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f088cc42-4914-49ca-8ade-a1aa849cc373)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/488f611a-54bc-494c-bf97-5302f8f5ac43)

**Comment by benlevy0** [comment]
A reliable way to repro this on my iPad is to create a market. The issue appears right after selecting the template subcategory, on both portrait and landscape views.

**Comment by bconfortin** [comment]
I've moved the issue for the top bar being cut, mentioned by Ben, to a different ticket: #8548.

**Comment by matt-bullock** [comment]
looks fixed. Closing
