### ISSUE TITLE
Hotloaded Market List UX Improvements

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#8489]
Anything that can be done to make the reloading not so jarring?

**Comment by pgebheim** [comment]
@bthaile making this because we never did :-D

**Comment by matt-bullock** [comment]
How about showing loading spinners in the spots that are still loading info. That way the info like market title loads immediately and nothing jumps around when the rest of the info loads. This informs the user that something is happening rather than just leaving it blank

Prototype (can take a while to load!): https://framer.com/share/Trading-Hot-Loading-Animations-5xmNPfVviezZpCuMbPy2/iIgD0q6Wi?fullscreen=1&highlights=0

![image](https://user-images.githubusercontent.com/39496225/89164851-ebac8d00-d577-11ea-849b-0d5325d4c9eb.png)
