### ISSUE TITLE
Onboarding: Flow - User has no tokens but wants to buy less than 50k Buys ETH and converts ETH to DAI (recommended)

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9197]
Bankrole screen should come before the user is asked to get ETH

See flow
https://www.figma.com/file/mhImzKiTrvaMpSm1lQ5KcL/New-Onboarding-Flow?node-id=0%3A1

**Comment by andrewdamelio** [comment]
@matt-bullock to me this flow doesn't make sense since we say we are going to  jump them o the in-app convertor (from bankroll) but instead we show them the deposit step and the swap step after - this is confusing...

I recommend we leave this as is (Deposit than Bankroll), since this follows the same flow as all the other scenarios

**Comment by matt-bullock** [comment]
Sure, maybe the order got mixed up in the design. Will close
