### ISSUE TITLE
Acronyms should be all caps UFC, MMA, NFL etc when filtering markets

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9701]
I'm seeing sentence case when filtering markets by categories

![image](https://user-images.githubusercontent.com/39496225/98959217-5d935b80-2503-11eb-98a6-9455ae6d7640.png)

**Comment by JohnDanz** [comment]
What's the rule here... like categories with 3 or less characters should be UPPERCASE? I ask because we don't have, nor will we/should we have, any way of knowing what tags might be in there and if they are acronyms or not. I know this is sports book, but there are a number of markets with a 3rd category left open to users to type into. In theory they could type whatever they want and that would be a searchable and displayable on the top of the page like in the screen shots. Generally our rule has been to assume that 3 letter or less words are actually acronyms and are automatically UPPERCASED. Anything with more 3 letters is treated like any other word and is simply Capitalized, not UPPERCASED. Should we assume the same rule here or leave it? @matt-bullock

**Comment by matt-bullock** [comment]
Making all caps should has fixed this. Still needs some tweaks to font sizes
