### ISSUE TITLE
Balance Tooltip Update

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#982]
We recently added the ability to mouse over the Balance section on the top bar to show Available Balance and Portfolio Balance of ETH. I propose we also add a number for REP to show REP in wallet vs total REP in wallet + Staked REP/Escrowed REP in a market bond.

<img width="341" alt="screen shot 2019-02-07 at 10 07 58 am" src="https://user-images.githubusercontent.com/10524630/52424831-68b09080-2ac0-11e9-8508-26f5ac5ee1a0.png">

Above is an example of what's currently shown.

**Comment by adrake33** [comment]
@JohnDanz I realize you filed this before Paul mentioned the new workflow process (https://github.com/AugurProject/augur/blob/0cd370c99f1e0a18c9ec02a5367e9936f0e46817/issues-workflow.md) on Discord, but for future tickets, please add V2 as the release unless the issue is for something that will only affect v1. Also, please be sure to add the Product Critical label if the issue's epic is also Product Critical and set the pipeline to Backlog if it doesn't need to be immediately worked on. Thanks!
